import traceback

from pyrx import Ap, Ax, Db, Ed


# ---------------------------------------------------------
# Method 1: Using the native API (Deep Clone)
# ---------------------------------------------------------
def deep_clone(id: Db.ObjectId):
    """
    Deep clones a database object (like a BlockReference) 
    into the current database using the native API.
    """
    # Get the database of the object being cloned
    db = id.database()
    
    # Get the DbObject for the source object
    dbo = Db.DbObject(id)
    
    # Create an IdMapping object to track the relationship between 
    # original IDs and new IDs during the clone process.
    idmap = Db.IdMapping()
    
    # Set the destination database for the clone operation.
    # This ensures the cloned object is added to the current drawing.
    idmap.setDestDb(db)
    
    # Perform the deep clone.
    # deepCloneObjects copies the object and any dependent objects 
    # (like the block definition it points to).
    db.deepCloneObjects([id], dbo.ownerId(), idmap)
    
    # Iterate through the mapping pairs to find the new ID created for our source object.
    for pr in idmap.idPairs():
        if pr.key() == id:
            # pr.value() is the new ObjectId generated by the cloning operation
            # Open it for write to ensure it is fully instantiated.
            clone = Db.Entity(pr.value(), Db.OpenMode.kForWrite)
            
            # Mark the clone as having modified graphics (required for AutoCAD to 
            # regenerate the object when the drawing is refreshed).
            clone.recordGraphicsModified()
            
            return pr.value()


# ---------------------------------------------------------
# Method 2: Using ActiveX (COM Interop)
# ---------------------------------------------------------
def ax_copy(id: Db.ObjectId):
    """
    Clones an object using the ActiveX (COM) interface.
    This is often used as a fallback or for specific ActiveX features.
    """
    # Check if the object is an Entity (BlockReferences are Entities).
    if id.isDerivedFrom(Db.Entity.desc()):
        # Cast the native object to an AcadEntity (ActiveX interface).
        # This allows calling COM methods like .copy().
        axe = Ax.AcadEntity.cast(id.acadObject())
        
        # Call the ActiveX copy method, which returns a new object in memory.
        # We then retrieve its ObjectId from the AutoCAD database.
        return axe.copy().objectId()


# ---------------------------------------------------------
# Verification Logic
# ---------------------------------------------------------
def doTest(origid: Db.ObjectId, cloneid: Db.ObjectId):
    """
    Compares the original and cloned BlockReferences to ensure 
    they are distinct objects but share the same definition.
    """
    # 1. Verify they are different objects in the database.
    print(origid != cloneid)
    
    # Create wrappers for both objects.
    orig = Db.BlockReference(origid)
    clone = Db.BlockReference(cloneid)
    
    # 2. Verify they point to the same BlockTableRecord (the definition).
    # Even though the BlockReference is different, it should reference 
    # the same block definition (e.g., "Standard").
    print(orig.blockTableRecord() == clone.blockTableRecord())

    # 3. Verify the Block Name matches.
    print(
        orig.getBlockName() == clone.getBlockName(),
        orig.getBlockName(),
        clone.getBlockName(),
    )

    # 4. Verify Dynamic Properties (if applicable).
    # We assume the objects are DynBlockReferences.
    dyn_orig = Db.DynBlockReference(origid)
    dyn_clone = Db.DynBlockReference(cloneid)

    # Iterate through properties and ensure names match.
    for o, c in zip(dyn_orig.getBlockProperties(), dyn_clone.getBlockProperties()):
        if o.propertyName() != c.propertyName():
            print("fail", o.propertyName(), c.propertyName())


# ---------------------------------------------------------
# Command Definitions
# ---------------------------------------------------------
@Ap.Command()
def doit1():
    """
    Command to test the Deep Clone method.
    """
    try:
        # Prompt the user to select a BlockReference.
        # Returns (status, ObjectId, point)
        _, origid, _ = Ed.Editor.entSel("\nGetIt: ", Db.BlockReference.desc())
        
        # Perform the deep clone.
        cloneid = deep_clone(origid)

        # Run the verification tests.
        doTest(origid, cloneid)

    except Exception as err:
        traceback.print_exception(err)


@Ap.Command()
def doit2():
    """
    Command to test the ActiveX Copy method.
    """
    try:
        _, origid, _ = Ed.Editor.entSel("\nGetIt: ", Db.BlockReference.desc())
        
        # Perform the ActiveX copy.
        cloneid = ax_copy(origid)

        # Run the verification tests.
        doTest(origid, cloneid)

    except Exception as err:
        traceback.print_exception(err)
