from _typeshed import Incomplete
from win32com.client import CoClassBaseClass, DispatchBaseClass
import BxDb24 as Db

makepy_version: str
python_version: int
defaultNamedOptArg: Incomplete
defaultNamedNotOptArg: Incomplete
defaultUnnamedArg: Incomplete
CLSID: Incomplete
MajorVersion: int
MinorVersion: int
LibraryFlags: int
LCID: int

def getApp() -> IAcadApplication: ...
def createEventObject(obj,eventClass): ...

class constants:
    acLsAll: int
    acLsColor: int
    acLsFrozen: int
    acLsLineType: int
    acLsLineWeight: int
    acLsLocked: int
    acLsNewViewport: int
    acLsNone: int
    acLsOn: int
    acLsPlot: int
    acLsPlotStyle: int
    ACADSECURITYPARAMS_ALGID_RC4: int
    ACADSECURITYPARAMS_ADD_TIMESTAMP: int
    ACADSECURITYPARAMS_ENCRYPT_DATA: int
    ACADSECURITYPARAMS_ENCRYPT_PROPS: int
    ACADSECURITYPARAMS_SIGN_DATA: int
    odDwfAscii: int
    odDwfCompressedBinary: int
    odDwfUncompressedBinary: int
    odDwf_v42: int
    odDwf_v55: int
    odDwf_v60: int
    od2000_Template: int
    od2000_dwg: int
    od2000_dxf: int
    od2004_Template: int
    od2004_dwg: int
    od2004_dxf: int
    od2007_Template: int
    od2007_dwg: int
    od2007_dxf: int
    od2010_Template: int
    od2010_dwg: int
    od2010_dxf: int
    od2013_Template: int
    od2013_dwg: int
    od2013_dxf: int
    od2018_Template: int
    od2018_dwg: int
    od2018_dxf: int
    odNative: int
    odR09_dxf: int
    odR10_dxf: int
    odR12_dwg: int
    odR12_dxf: int
    odR13_dwg: int
    odR13_dxf: int
    odR14_dwg: int
    odR14_dxf: int
    odR15_Template: int
    odR15_dwg: int
    odR15_dxf: int
    odR18_Template: int
    odR18_dwg: int
    odR18_dxf: int
    odR21_Template: int
    odR21_dwg: int
    odR21_dxf: int
    odR24_Template: int
    odR24_dwg: int
    odR24_dxf: int
    odR27_Template: int
    odR27_dwg: int
    odR27_dxf: int
    odR32_Template: int
    odR32_dwg: int
    odR32_dxf: int
    odUnknown: int
    PDFEXPORT_EXCLUDE_OFFLAYER: int
    PDFEXPORT_INCLUDE_OFFLAYER: int
    PDFEXPORT_NOLAYER: int
    PDFEXPORT_LAYOUTS_ACTIVE: int
    PDFEXPORT_LAYOUTS_ALL: int
    e3rdPartyAddedFile: int
    eAltFontFile: int
    eDGNUnderlay: int
    eDWFUnderlay: int
    eDataLinkFile: int
    eDwgFile: int
    eEdgeTextureFile: int
    eFontFile: int
    eFontMapFile: int
    eGeneratedFile: int
    eImageFile: int
    eMaterialTextureFile: int
    eNoType: int
    ePDFUnderlay: int
    ePfbAltFontFile: int
    ePfbFontFile: int
    ePhotometricWebFile: int
    ePlotCfgFile: int
    ePlotStyleTableFile: int
    eSheetSetFile: int
    eSheetSetSupportFile: int
    eShxAltFontFile: int
    eShxFontFile: int
    eTtfAltFontFile: int
    eTtfFontFile: int
    eUserAddedFile: int
    eXrefAttachFile: int
    eXrefFile: int
    eXrefOverlayFile: int
    eFileAdded: int
    eFileAlreadyAdded: int
    eFileNotAdded: int
    eFileNotAddedBadArg: int
    eFileNotAddedToPreventCycle: int
    eRelationshipAdded: int
    eAutoCAD14: int
    eAutoCAD2000: int
    eAutoCADR18: int
    eAutoCADR21: int
    eNoConversion: int
    eOverwriteCancel: int
    eOverwriteNo: int
    eOverwriteYes: int
    eOverwriteYesToAll: int
    eOverwriteYesToAllReadOnly: int

class IAcadApplication(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def DefineFunction(self, FunctionName=..., FunctionPointer=...): ...
    def Eval(self, Expression=...): ...
    def GetAcadState(self): ...
    def GetInterfaceObject(self, ProgID=...): ...
    def ListArx(self): ...
    def LoadArx(self, Name=...): ...
    def LoadDVB(self, Name=...): ...
    def Quit(self): ...
    def RunCommand(self, Command=...): ...
    def RunMacro(self, MacroPath=...): ...
    def RunScript(self, Script=...): ...
    def StatusId(self, VportObj=...): ...
    def UndefineFunction(self, FunctionName=...): ...
    def UnloadArx(self, Name=...): ...
    def UnloadDVB(self, Name=...): ...
    def Update(self): ...
    def Zoom(self, Type=..., vParams=...): ...
    def ZoomAll(self): ...
    def ZoomCenter(self, Center=..., Magnify=...): ...
    def ZoomExtents(self): ...
    def ZoomPickWindow(self): ...
    def ZoomPrevious(self): ...
    def ZoomScaled(self, scale=..., ScaleType=...): ...
    def ZoomWindow(self, LowerLeft=..., UpperRight=...): ...
    def __iter__(self): ...
    @property
    def ActiveDocument(self) -> IAcadDocument: ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Caption(self): ...
    @property
    def Documents(self) -> IAcadDocuments: ...
    @property
    def FullName(self): ...
    @property
    def HWND(self): ...
    @property
    def Height(self): ...
    @property
    def LocaleId(self): ...
    @property
    def MenuBar(self) -> IAcadMenuBar: ...
    @property
    def MenuGroups(self) -> IAcadMenuGroups: ...
    @property
    def Name(self): ...
    @property
    def Path(self): ...
    @property
    def Preferences(self) -> IAcadPreferences: ...
    @property
    def VBE(self): ...
    @property
    def Version(self): ...
    @property
    def Visible(self): ...
    @property
    def Width(self): ...
    @property
    def WindowLeft(self): ...
    @property
    def WindowState(self): ...
    @property
    def WindowTop(self): ...
    @ActiveDocument.setter
    def ActiveDocument(self, value) -> None: ...
    @Height.setter
    def Height(self, value) -> None: ...
    @Visible.setter
    def Visible(self, value) -> None: ...
    @Width.setter
    def Width(self, value) -> None: ...
    @WindowLeft.setter
    def WindowLeft(self, value) -> None: ...
    @WindowState.setter
    def WindowState(self, value) -> None: ...
    @WindowTop.setter
    def WindowTop(self, value) -> None: ...
    

class IAcadDocument(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def AbortTransaction(self): ...
    def Activate(self): ...
    def AuditInfo(self, FixErr=...): ...
    def Close(self, SaveChanges=..., FileName=...): ...
    def CopyObjects(self, Objects=..., Owner=..., IdPairs=...): ...
    def EndTransaction(self): ...
    def EndUndoMark(self): ...
    def EvaluateLisp(self, lispString=...): ...
    def Export(self, FileName=..., Extension=..., SelectionSet=...): ...
    def GetVariable(self, Name=...): ...
    def HandleToObject(self, Handle=...): ...
    def Import(self, FileName=..., InsertionPoint=..., ScaleFactor=...): ...
    def LoadShapeFile(self, FullName=...): ...
    def New(self, TemplateFileName=...): ...
    def ObjectIdToObject(self, ObjectID=...): ...
    def ObjectIdToObject32(self, ObjectID=...): ...
    def Open(self, FullName=..., Password=...): ...
    def PurgeAll(self): ...
    def Regen(self, WhichViewports=...): ...
    def Save(self): ...
    def SaveAs(self, FullFileName=..., SaveAsType=..., vSecurityParams=...): ...
    def SendCommand(self, Command=...): ...
    def SetVariable(self, Name=..., Value=...): ...
    def StartTransaction(self): ...
    def StartUndoMark(self): ...
    def Wblock(self, FileName=..., SelectionSet=...): ...
    def getTransmittalOperationInterface(self): ...
    def __iter__(self): ...
    @property
    def Active(self): ...
    @property
    def ActiveDimStyle(self) -> Db.IAcadDimStyle: ...
    @property
    def ActiveLayer(self) -> Db.IAcadLayer: ...
    @property
    def ActiveLayout(self) -> Db.IAcadLayout: ...
    @property
    def ActiveLinetype(self) -> Db.IAcadLineType: ...
    @property
    def ActiveMaterial(self) -> Db.IAcadMaterial: ...
    @property
    def ActivePViewport(self) -> Db.IAcadPViewport: ...
    @property
    def ActiveSelectionSet(self) -> IAcadSelectionSet: ...
    @property
    def ActiveSpace(self): ...
    @property
    def ActiveTextStyle(self) -> Db.IAcadTextStyle: ...
    @property
    def ActiveUCS(self) -> Db.IAcadUCS: ...
    @property
    def ActiveViewport(self) -> Db.IAcadViewport: ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Blocks(self) -> Db.IAcadBlocks: ...
    @property
    def Database(self) -> Db.IAcadDatabase: ...
    @property
    def Dictionaries(self) -> Db.IAcadDictionaries: ...
    @property
    def DimStyles(self) -> Db.IAcadDimStyles: ...
    @property
    def ElevationModelSpace(self): ...
    @property
    def ElevationPaperSpace(self): ...
    @property
    def FullName(self): ...
    @property
    def Groups(self) -> Db.IAcadGroups: ...
    @property
    def HWND(self): ...
    @property
    def Height(self): ...
    @property
    def Layers(self) -> Db.IAcadLayers: ...
    @property
    def Layouts(self) -> Db.IAcadLayouts: ...
    @property
    def Limits(self): ...
    @property
    def Linetypes(self) -> Db.IAcadLineTypes: ...
    @property
    def MSpace(self): ...
    @property
    def Materials(self) -> Db.IAcadMaterials: ...
    @property
    def ModelSpace(self) -> Db.IAcadModelSpace: ...
    @property
    def Name(self): ...
    @property
    def ObjectSnapMode(self): ...
    @property
    def PaperSpace(self) -> Db.IAcadPaperSpace: ...
    @property
    def Path(self): ...
    @property
    def PickfirstSelectionSet(self) -> IAcadSelectionSet: ...
    @property
    def Plot(self) -> IAcadPlot: ...
    @property
    def PlotConfigurations(self) -> Db.IAcadPlotConfigurations: ...
    @property
    def Preferences(self) -> Db.IAcadDatabasePreferences: ...
    @property
    def ReadOnly(self): ...
    @property
    def RegisteredApplications(self) -> Db.IAcadRegisteredApplications: ...
    @property
    def Saved(self): ...
    @property
    def SectionManager(self) -> Db.IAcadSectionManager: ...
    @property
    def SelectionSets(self) -> IAcadSelectionSets: ...
    @property
    def SummaryInfo(self) -> Db.IAcadSummaryInfo: ...
    @property
    def TextStyles(self) -> Db.IAcadTextStyles: ...
    @property
    def UserCoordinateSystems(self) -> Db.IAcadUCSs: ...
    @property
    def Utility(self) -> IAcadUtility: ...
    @property
    def Viewports(self) -> Db.IAcadViewports: ...
    @property
    def Views(self) -> Db.IAcadViews: ...
    @property
    def Width(self): ...
    @property
    def WindowState(self): ...
    @property
    def WindowTitle(self): ...
    @ActiveDimStyle.setter
    def ActiveDimStyle(self, value) -> None: ...
    @ActiveLayer.setter
    def ActiveLayer(self, value) -> None: ...
    @ActiveLayout.setter
    def ActiveLayout(self, value) -> None: ...
    @ActiveLinetype.setter
    def ActiveLinetype(self, value) -> None: ...
    @ActiveMaterial.setter
    def ActiveMaterial(self, value) -> None: ...
    @ActivePViewport.setter
    def ActivePViewport(self, value) -> None: ...
    @ActiveSpace.setter
    def ActiveSpace(self, value) -> None: ...
    @ActiveTextStyle.setter
    def ActiveTextStyle(self, value) -> None: ...
    @ActiveUCS.setter
    def ActiveUCS(self, value) -> None: ...
    @ActiveViewport.setter
    def ActiveViewport(self, value) -> None: ...
    @ElevationModelSpace.setter
    def ElevationModelSpace(self, value) -> None: ...
    @ElevationPaperSpace.setter
    def ElevationPaperSpace(self, value) -> None: ...
    @Height.setter
    def Height(self, value) -> None: ...
    @Limits.setter
    def Limits(self, value) -> None: ...
    @MSpace.setter
    def MSpace(self, value) -> None: ...
    @ObjectSnapMode.setter
    def ObjectSnapMode(self, value) -> None: ...
    @Width.setter
    def Width(self, value) -> None: ...
    @WindowState.setter
    def WindowState(self, value) -> None: ...

class IAcadDocuments(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Add(self, TemplateName=...): ...
    def Close(self): ...
    def Item(self, Index=...): ...
    def Open(self, Name=..., ReadOnly=..., Password=...): ...
    def __call__(self, Index=...): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Count(self): ...

class IAcadLayerStateManager(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Delete(self, bsName=...): ...
    def Export(self, bsName=..., bsFilename=...): ...
    def Import(self, bsFilename=...): ...
    def Mask(self, bsName=...): ...
    def Rename(self, bsName=..., bsNewName=...): ...
    def Restore(self, bsName=...): ...
    def Save(self, bsName=..., eMask=...): ...
    def SetDatabase(self, iHostDb=...): ...
    def SetMask(self, bsName=..., arg1=...): ...
    def __iter__(self): ...

class IAcadMenuBar(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Item(self, Index=...): ...
    def __call__(self, Index=...): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Count(self): ...
    @property
    def Parent(self): ...

class IAcadMenuGroup(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Save(self, MenuFileType=...): ...
    def SaveAs(self, MenuFileName=..., MenuFileType=...): ...
    def Unload(self): ...
    def __iter__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def MenuFileName(self): ...
    @property
    def Menus(self): ...
    @property
    def Name(self): ...
    @property
    def Parent(self): ...
    @property
    def Toolbars(self): ...
    @property
    def Type(self): ...

class IAcadMenuGroups(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Item(self, Index=...): ...
    def Load(self, MenuFileName=..., BaseMenu=...): ...
    def __call__(self, Index=...): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...

class IAcadPlot(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def DisplayPlotPreview(self, PreviewMode=...): ...
    def PlotToDevice(self, plotConfig=...): ...
    def PlotToFile(self, plotFile=..., plotConfig=...): ...
    def SetLayoutsToPlot(self, layoutList=...): ...
    def StartBatchMode(self, entryCount=...): ...
    def __iter__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Count(self): ...
    @property
    def Parent(self): ...

class IAcadPopupMenu(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def AddMenuItem(self, Index=..., Label=..., Macro=...): ...
    def AddSeparator(self, Index=...): ...
    def AddSubMenu(self, Index=..., Label=...): ...
    def InsertInMenuBar(self, Index=...): ...
    def Item(self, Index=...): ...
    def RemoveFromMenuBar(self): ...
    def __call__(self, Index=...): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Count(self): ...
    @property
    def Name(self): ...
    @property
    def NameNoMnemonic(self): ...
    @property
    def OnMenuBar(self): ...
    @property
    def Parent(self): ...
    @property
    def ShortcutMenu(self): ...
    @property
    def TagString(self): ...
    @Name.setter
    def Name(self, value) -> None: ...

class IAcadPopupMenuItem(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Delete(self): ...
    def __iter__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Caption(self): ...
    @property
    def Check(self): ...
    @property
    def Enable(self): ...
    @property
    def EndSubMenuLevel(self): ...
    @property
    def HelpString(self): ...
    @property
    def Index(self): ...
    @property
    def Label(self): ...
    @property
    def Macro(self): ...
    @property
    def Parent(self): ...
    @property
    def SubMenu(self): ...
    @property
    def TagString(self): ...
    @property
    def Type(self): ...
    @Check.setter
    def Check(self, value) -> None: ...
    @Enable.setter
    def Enable(self, value) -> None: ...
    @EndSubMenuLevel.setter
    def EndSubMenuLevel(self, value) -> None: ...
    @HelpString.setter
    def HelpString(self, value) -> None: ...
    @Label.setter
    def Label(self, value) -> None: ...
    @Macro.setter
    def Macro(self, value) -> None: ...
    @TagString.setter
    def TagString(self, value) -> None: ...

class IAcadPopupMenus(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Add(self, MenuName=...): ...
    def InsertMenuInMenuBar(self, MenuName=..., Index=...): ...
    def Item(self, Index=...): ...
    def RemoveMenuFromMenuBar(self, Index=...): ...
    def __call__(self, Index=...): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Count(self): ...
    @property
    def Parent(self): ...

class IAcadPreferences(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Display(self): ...
    @property
    def Drafting(self): ...
    @property
    def Files(self): ...
    @property
    def OpenSave(self): ...
    @property
    def Output(self): ...
    @property
    def Profiles(self): ...
    @property
    def Selection(self): ...
    @property
    def System(self): ...
    @property
    def User(self): ...

class IAcadPreferencesDisplay(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def AutoTrackingVecColor(self): ...
    @property
    def CursorSize(self): ...
    @property
    def DisplayLayoutTabs(self): ...
    @property
    def DisplayScreenMenu(self): ...
    @property
    def DisplayScrollBars(self): ...
    @property
    def DockedVisibleLines(self): ...
    @property
    def GraphicsWinLayoutBackgrndColor(self): ...
    @property
    def GraphicsWinModelBackgrndColor(self): ...
    @property
    def HistoryLines(self): ...
    @property
    def ImageFrameHighlight(self): ...
    @property
    def LayoutCreateViewport(self): ...
    @property
    def LayoutCrosshairColor(self): ...
    @property
    def LayoutDisplayMargins(self): ...
    @property
    def LayoutDisplayPaper(self): ...
    @property
    def LayoutDisplayPaperShadow(self): ...
    @property
    def LayoutShowPlotSetup(self): ...
    @property
    def MaxAutoCADWindow(self): ...
    @property
    def ModelCrosshairColor(self): ...
    @property
    def ShowRasterImage(self): ...
    @property
    def TextFont(self): ...
    @property
    def TextFontSize(self): ...
    @property
    def TextFontStyle(self): ...
    @property
    def TextWinBackgrndColor(self): ...
    @property
    def TextWinTextColor(self): ...
    @property
    def TrueColorImages(self): ...
    @property
    def XRefFadeIntensity(self): ...
    @AutoTrackingVecColor.setter
    def AutoTrackingVecColor(self, value) -> None: ...
    @CursorSize.setter
    def CursorSize(self, value) -> None: ...
    @DisplayLayoutTabs.setter
    def DisplayLayoutTabs(self, value) -> None: ...
    @DisplayScreenMenu.setter
    def DisplayScreenMenu(self, value) -> None: ...
    @DisplayScrollBars.setter
    def DisplayScrollBars(self, value) -> None: ...
    @DockedVisibleLines.setter
    def DockedVisibleLines(self, value) -> None: ...
    @GraphicsWinLayoutBackgrndColor.setter
    def GraphicsWinLayoutBackgrndColor(self, value) -> None: ...
    @GraphicsWinModelBackgrndColor.setter
    def GraphicsWinModelBackgrndColor(self, value) -> None: ...
    @HistoryLines.setter
    def HistoryLines(self, value) -> None: ...
    @ImageFrameHighlight.setter
    def ImageFrameHighlight(self, value) -> None: ...
    @LayoutCreateViewport.setter
    def LayoutCreateViewport(self, value) -> None: ...
    @LayoutCrosshairColor.setter
    def LayoutCrosshairColor(self, value) -> None: ...
    @LayoutDisplayMargins.setter
    def LayoutDisplayMargins(self, value) -> None: ...
    @LayoutDisplayPaper.setter
    def LayoutDisplayPaper(self, value) -> None: ...
    @LayoutDisplayPaperShadow.setter
    def LayoutDisplayPaperShadow(self, value) -> None: ...
    @LayoutShowPlotSetup.setter
    def LayoutShowPlotSetup(self, value) -> None: ...
    @MaxAutoCADWindow.setter
    def MaxAutoCADWindow(self, value) -> None: ...
    @ModelCrosshairColor.setter
    def ModelCrosshairColor(self, value) -> None: ...
    @ShowRasterImage.setter
    def ShowRasterImage(self, value) -> None: ...
    @TextFont.setter
    def TextFont(self, value) -> None: ...
    @TextFontSize.setter
    def TextFontSize(self, value) -> None: ...
    @TextFontStyle.setter
    def TextFontStyle(self, value) -> None: ...
    @TextWinBackgrndColor.setter
    def TextWinBackgrndColor(self, value) -> None: ...
    @TextWinTextColor.setter
    def TextWinTextColor(self, value) -> None: ...
    @TrueColorImages.setter
    def TrueColorImages(self, value) -> None: ...
    @XRefFadeIntensity.setter
    def XRefFadeIntensity(self, value) -> None: ...

class IAcadPreferencesDrafting(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...
    @property
    def AlignmentPointAcquisition(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def AutoSnapAperture(self): ...
    @property
    def AutoSnapApertureSize(self): ...
    @property
    def AutoSnapMagnet(self): ...
    @property
    def AutoSnapMarker(self): ...
    @property
    def AutoSnapMarkerColor(self): ...
    @property
    def AutoSnapMarkerSize(self): ...
    @property
    def AutoSnapTooltip(self): ...
    @property
    def AutoTrackTooltip(self): ...
    @property
    def FullScreenTrackingVector(self): ...
    @property
    def PolarTrackingVector(self): ...
    @AlignmentPointAcquisition.setter
    def AlignmentPointAcquisition(self, value) -> None: ...
    @AutoSnapAperture.setter
    def AutoSnapAperture(self, value) -> None: ...
    @AutoSnapApertureSize.setter
    def AutoSnapApertureSize(self, value) -> None: ...
    @AutoSnapMagnet.setter
    def AutoSnapMagnet(self, value) -> None: ...
    @AutoSnapMarker.setter
    def AutoSnapMarker(self, value) -> None: ...
    @AutoSnapMarkerColor.setter
    def AutoSnapMarkerColor(self, value) -> None: ...
    @AutoSnapMarkerSize.setter
    def AutoSnapMarkerSize(self, value) -> None: ...
    @AutoSnapTooltip.setter
    def AutoSnapTooltip(self, value) -> None: ...
    @AutoTrackTooltip.setter
    def AutoTrackTooltip(self, value) -> None: ...
    @FullScreenTrackingVector.setter
    def FullScreenTrackingVector(self, value) -> None: ...
    @PolarTrackingVector.setter
    def PolarTrackingVector(self, value) -> None: ...


class IAcadPreferencesFiles(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def GetProjectFilePath(self, ProjectName=...): ...
    def SetProjectFilePath(self, ProjectName=..., ProjectFilePath=...): ...
    def __call__(self): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    @property
    def ActiveInvProject(self): ...
    @property
    def AltFontFile(self): ...
    @property
    def AltTabletMenuFile(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def AutoSavePath(self): ...
    @property
    def ColorBookPath(self): ...
    @property
    def ConfigFile(self): ...
    @property
    def CustomDictionary(self): ...
    @property
    def CustomIconPath(self): ...
    @property
    def DefaultInternetURL(self): ...
    @property
    def DriversPath(self): ...
    @property
    def EnterpriseMenuFile(self): ...
    @property
    def FontFileMap(self): ...
    @property
    def HelpFilePath(self): ...
    @property
    def LicenseServer(self): ...
    @property
    def LogFilePath(self): ...
    @property
    def MainDictionary(self): ...
    @property
    def MenuFile(self): ...
    @property
    def ObjectARXPath(self): ...
    @property
    def PageSetupOverridesTemplateFile(self): ...
    @property
    def PlotLogFilePath(self): ...
    @property
    def PostScriptPrologFile(self): ...
    @property
    def PrintFile(self): ...
    @property
    def PrintSpoolExecutable(self): ...
    @property
    def PrintSpoolerPath(self): ...
    @property
    def PrinterConfigPath(self): ...
    @property
    def PrinterDescPath(self): ...
    @property
    def PrinterStyleSheetPath(self): ...
    @property
    def QNewTemplateFile(self): ...
    @property
    def SupportPath(self): ...
    @property
    def TempFilePath(self): ...
    @property
    def TempXrefPath(self): ...
    @property
    def TemplateDwgPath(self): ...
    @property
    def TextEditor(self): ...
    @property
    def TextureMapPath(self): ...
    @property
    def ToolPalettePath(self): ...
    @property
    def WorkspacePath(self): ...
    @ActiveInvProject.setter
    def ActiveInvProject(self, value) -> None: ...
    @AltFontFile.setter
    def AltFontFile(self, value) -> None: ...
    @AltTabletMenuFile.setter
    def AltTabletMenuFile(self, value) -> None: ...
    @AutoSavePath.setter
    def AutoSavePath(self, value) -> None: ...
    @ColorBookPath.setter
    def ColorBookPath(self, value) -> None: ...
    @CustomDictionary.setter
    def CustomDictionary(self, value) -> None: ...
    @CustomIconPath.setter
    def CustomIconPath(self, value) -> None: ...
    @DefaultInternetURL.setter
    def DefaultInternetURL(self, value) -> None: ...
    @DriversPath.setter
    def DriversPath(self, value) -> None: ...
    @EnterpriseMenuFile.setter
    def EnterpriseMenuFile(self, value) -> None: ...
    @FontFileMap.setter
    def FontFileMap(self, value) -> None: ...
    @HelpFilePath.setter
    def HelpFilePath(self, value) -> None: ...
    @LogFilePath.setter
    def LogFilePath(self, value) -> None: ...
    @MainDictionary.setter
    def MainDictionary(self, value) -> None: ...
    @MenuFile.setter
    def MenuFile(self, value) -> None: ...
    @ObjectARXPath.setter
    def ObjectARXPath(self, value) -> None: ...
    @PageSetupOverridesTemplateFile.setter
    def PageSetupOverridesTemplateFile(self, value) -> None: ...
    @PlotLogFilePath.setter
    def PlotLogFilePath(self, value) -> None: ...
    @PostScriptPrologFile.setter
    def PostScriptPrologFile(self, value) -> None: ...
    @PrintFile.setter
    def PrintFile(self, value) -> None: ...
    @PrintSpoolExecutable.setter
    def PrintSpoolExecutable(self, value) -> None: ...
    @PrintSpoolerPath.setter
    def PrintSpoolerPath(self, value) -> None: ...
    @PrinterConfigPath.setter
    def PrinterConfigPath(self, value) -> None: ...
    @PrinterDescPath.setter
    def PrinterDescPath(self, value) -> None: ...
    @PrinterStyleSheetPath.setter
    def PrinterStyleSheetPath(self, value) -> None: ...
    @QNewTemplateFile.setter
    def QNewTemplateFile(self, value) -> None: ...
    @SupportPath.setter
    def SupportPath(self, value) -> None: ...
    @TempFilePath.setter
    def TempFilePath(self, value) -> None: ...
    @TempXrefPath.setter
    def TempXrefPath(self, value) -> None: ...
    @TemplateDwgPath.setter
    def TemplateDwgPath(self, value) -> None: ...
    @TextEditor.setter
    def TextEditor(self, value) -> None: ...
    @TextureMapPath.setter
    def TextureMapPath(self, value) -> None: ...
    @ToolPalettePath.setter
    def ToolPalettePath(self, value) -> None: ...
    @WorkspacePath.setter
    def WorkspacePath(self, value) -> None: ...

class IAcadPreferencesOpenSave(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def AutoAudit(self): ...
    @property
    def AutoSaveInterval(self): ...
    @property
    def CreateBackup(self): ...
    @property
    def DemandLoadARXApp(self): ...
    @property
    def FullCRCValidation(self): ...
    @property
    def IncrementalSavePercent(self): ...
    @property
    def LogFileOn(self): ...
    @property
    def MRUNumber(self): ...
    @property
    def ProxyImage(self): ...
    @property
    def SaveAsType(self): ...
    @property
    def SavePreviewThumbnail(self): ...
    @property
    def ShowProxyDialogBox(self): ...
    @property
    def TempFileExtension(self): ...
    @property
    def XrefDemandLoad(self): ...
    @AutoAudit.setter
    def AutoAudit(self, value) -> None: ...
    @AutoSaveInterval.setter
    def AutoSaveInterval(self, value) -> None: ...
    @CreateBackup.setter
    def CreateBackup(self, value) -> None: ...
    @DemandLoadARXApp.setter
    def DemandLoadARXApp(self, value) -> None: ...
    @FullCRCValidation.setter
    def FullCRCValidation(self, value) -> None: ...
    @IncrementalSavePercent.setter
    def IncrementalSavePercent(self, value) -> None: ...
    @LogFileOn.setter
    def LogFileOn(self, value) -> None: ...
    @ProxyImage.setter
    def ProxyImage(self, value) -> None: ...
    @SaveAsType.setter
    def SaveAsType(self, value) -> None: ...
    @SavePreviewThumbnail.setter
    def SavePreviewThumbnail(self, value) -> None: ...
    @ShowProxyDialogBox.setter
    def ShowProxyDialogBox(self, value) -> None: ...
    @TempFileExtension.setter
    def TempFileExtension(self, value) -> None: ...
    @XrefDemandLoad.setter
    def XrefDemandLoad(self, value) -> None: ...

class IAcadPreferencesOutput(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def AutomaticPlotLog(self): ...
    @property
    def ContinuousPlotLog(self): ...
    @property
    def DefaultOutputDevice(self): ...
    @property
    def DefaultPlotStyleForLayer(self): ...
    @property
    def DefaultPlotStyleForObjects(self): ...
    @property
    def DefaultPlotStyleTable(self): ...
    @property
    def DefaultPlotToFilePath(self): ...
    @property
    def OLEQuality(self): ...
    @property
    def PlotLegacy(self): ...
    @property
    def PlotPolicy(self): ...
    @property
    def PrinterPaperSizeAlert(self): ...
    @property
    def PrinterSpoolAlert(self): ...
    @property
    def UseLastPlotSettings(self): ...
    @AutomaticPlotLog.setter
    def AutomaticPlotLog(self, value) -> None: ...
    @ContinuousPlotLog.setter
    def ContinuousPlotLog(self, value) -> None: ...
    @DefaultOutputDevice.setter
    def DefaultOutputDevice(self, value) -> None: ...
    @DefaultPlotStyleForLayer.setter
    def DefaultPlotStyleForLayer(self, value) -> None: ...
    @DefaultPlotStyleForObjects.setter
    def DefaultPlotStyleForObjects(self, value) -> None: ...
    @DefaultPlotStyleTable.setter
    def DefaultPlotStyleTable(self, value) -> None: ...
    @DefaultPlotToFilePath.setter
    def DefaultPlotToFilePath(self, value) -> None: ...
    @OLEQuality.setter
    def OLEQuality(self, value) -> None: ...
    @PlotLegacy.setter
    def PlotLegacy(self, value) -> None: ...
    @PlotPolicy.setter
    def PlotPolicy(self, value) -> None: ...
    @PrinterPaperSizeAlert.setter
    def PrinterPaperSizeAlert(self, value) -> None: ...
    @PrinterSpoolAlert.setter
    def PrinterSpoolAlert(self, value) -> None: ...
    @UseLastPlotSettings.setter
    def UseLastPlotSettings(self, value) -> None: ...

class IAcadPreferencesPdfOutput(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...

class IAcadPreferencesProfiles(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def CopyProfile(self, oldProfileName=..., newProfileName=...): ...
    def DeleteProfile(self, ProfileName=...): ...
    def ExportProfile(self, ProfileName=..., RegFile=...): ...
    def GetAllProfileNames(self, pNames=...): ...
    def ImportProfile(self, ProfileName=..., RegFile=..., IncludePathInfo=...): ...
    def RenameProfile(self, origProfileName=..., newProfileName=...): ...
    def ResetProfile(self, Profile=...): ...
    def __iter__(self): ...
    @property
    def ActiveProfile(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @ActiveProfile.setter
    def ActiveProfile(self, value) -> None: ...

class IAcadPreferencesSelection(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def DisplayGrips(self): ...
    @property
    def DisplayGripsWithinBlocks(self): ...
    @property
    def GripColorSelected(self): ...
    @property
    def GripColorUnselected(self): ...
    @property
    def GripSize(self): ...
    @property
    def PickAdd(self): ...
    @property
    def PickAuto(self): ...
    @property
    def PickBoxSize(self): ...
    @property
    def PickDrag(self): ...
    @property
    def PickFirst(self): ...
    @property
    def PickGroup(self): ...
    @DisplayGrips.setter
    def DisplayGrips(self, value) -> None: ...
    @DisplayGripsWithinBlocks.setter
    def DisplayGripsWithinBlocks(self, value) -> None: ...
    @GripColorSelected.setter
    def GripColorSelected(self, value) -> None: ...
    @GripColorUnselected.setter
    def GripColorUnselected(self, value) -> None: ...
    @GripSize.setter
    def GripSize(self, value) -> None: ...
    @PickAdd.setter
    def PickAdd(self, value) -> None: ...
    @PickAuto.setter
    def PickAuto(self, value) -> None: ...
    @PickBoxSize.setter
    def PickBoxSize(self, value) -> None: ...
    @PickDrag.setter
    def PickDrag(self, value) -> None: ...
    @PickFirst.setter
    def PickFirst(self, value) -> None: ...
    @PickGroup.setter
    def PickGroup(self, value) -> None: ...

class IAcadPreferencesSystem(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def BeepOnError(self): ...
    @property
    def DisplayOLEScale(self): ...
    @property
    def EnableStartupDialog(self): ...
    @property
    def LoadAcadLspInAllDocuments(self): ...
    @property
    def ShowWarningMessages(self): ...
    @property
    def SingleDocumentMode(self): ...
    @property
    def StoreSQLIndex(self): ...
    @property
    def TablesReadOnly(self): ...
    @BeepOnError.setter
    def BeepOnError(self, value) -> None: ...
    @DisplayOLEScale.setter
    def DisplayOLEScale(self, value) -> None: ...
    @EnableStartupDialog.setter
    def EnableStartupDialog(self, value) -> None: ...
    @LoadAcadLspInAllDocuments.setter
    def LoadAcadLspInAllDocuments(self, value) -> None: ...
    @ShowWarningMessages.setter
    def ShowWarningMessages(self, value) -> None: ...
    @SingleDocumentMode.setter
    def SingleDocumentMode(self, value) -> None: ...
    @StoreSQLIndex.setter
    def StoreSQLIndex(self, value) -> None: ...
    @TablesReadOnly.setter
    def TablesReadOnly(self, value) -> None: ...

class IAcadPreferencesUser(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...
    @property
    def ADCInsertUnitsDefaultSource(self): ...
    @property
    def ADCInsertUnitsDefaultTarget(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def HyperlinkDisplayCursor(self): ...
    @property
    def KeyboardAccelerator(self): ...
    @property
    def KeyboardPriority(self): ...
    @property
    def SCMCommandMode(self): ...
    @property
    def SCMDefaultMode(self): ...
    @property
    def SCMEditMode(self): ...
    @property
    def SCMTimeMode(self): ...
    @property
    def SCMTimeValue(self): ...
    @property
    def ShortCutMenuDisplay(self): ...
    @ADCInsertUnitsDefaultSource.setter
    def ADCInsertUnitsDefaultSource(self, value) -> None: ...
    @ADCInsertUnitsDefaultTarget.setter
    def ADCInsertUnitsDefaultTarget(self, value) -> None: ...
    @HyperlinkDisplayCursor.setter
    def HyperlinkDisplayCursor(self, value) -> None: ...
    @KeyboardAccelerator.setter
    def KeyboardAccelerator(self, value) -> None: ...
    @KeyboardPriority.setter
    def KeyboardPriority(self, value) -> None: ...
    @SCMCommandMode.setter
    def SCMCommandMode(self, value) -> None: ...
    @SCMDefaultMode.setter
    def SCMDefaultMode(self, value) -> None: ...
    @SCMEditMode.setter
    def SCMEditMode(self, value) -> None: ...
    @SCMTimeMode.setter
    def SCMTimeMode(self, value) -> None: ...
    @SCMTimeValue.setter
    def SCMTimeValue(self, value) -> None: ...
    @ShortCutMenuDisplay.setter
    def ShortCutMenuDisplay(self, value) -> None: ...
    
class IAcadSecurityParams(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...

class IAcadSelectionSet(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def AddItems(self, pSelSet=...): ...
    def Clear(self): ...
    def Delete(self): ...
    def Erase(self): ...
    def Highlight(self, bFlag=...): ...
    def Item(self, Index=...): ...
    def RemoveItems(self, Objects=...): ...
    def Select(self, Mode=..., Point1=..., Point2=..., FilterType=..., FilterData=...): ...
    def SelectAtPoint(self, Point=..., FilterType=..., FilterData=...): ...
    def SelectByPolygon(self, Mode=..., PointsList=..., FilterType=..., FilterData=...): ...
    def SelectOnScreen(self, FilterType=..., FilterData=...): ...
    def Update(self): ...
    def __call__(self, Index=...): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Count(self) -> int: ...
    @property
    def Name(self) -> str: ...

class IAcadSelectionSets(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Add(self, Name=...): ...
    def Item(self, Index=...): ...
    def __call__(self, Index=...): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...
    @property
    def Application(self) -> IAcadApplication: ...
    @property
    def Count(self) -> int: ...

class IAcadState(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...

class IAcadToolbar(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def AddSeparator(self, Index=...): ...
    def AddToolbarButton(self, Index=..., Name=..., HelpString=..., Macro=..., FlyoutButton=...): ...
    def Delete(self): ...
    def Dock(self, Side=...): ...
    def Float(self, top=..., left=..., NumberFloatRows=...): ...
    def Item(self, Index=...): ...
    def __call__(self, Index=...): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...

class IAcadToolbarItem(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def AttachToolbarToFlyout(self, MenuGroupName=..., ToolbarName=...): ...
    def Delete(self): ...
    def GetBitmaps(self, SmallIconName=..., LargeIconName=...): ...
    def SetBitmaps(self, SmallIconName=..., LargeIconName=...): ...
    def __iter__(self): ...

class IAcadToolbars(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Add(self, ToolbarName=...): ...
    def Item(self, Index=...): ...
    def __call__(self, Index=...): ...
    def __int__(self, *args) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...

class IAcadUtility(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def AngleFromXAxis(self, StartPoint=..., EndPoint=...): ...
    def AngleToReal(self, Angle=..., Unit=...): ...
    def AngleToString(self, Angle=..., Unit=..., precision=...): ...
    def CreateTypedArray(self, *args): ...
    def DistanceToReal(self, Distance=..., Unit=...): ...
    def GetAngle(self, Point=..., Prompt=...): ...
    def GetCorner(self, Point=..., Prompt=...): ...
    def GetDistance(self, Point=..., Prompt=...): ...
    def GetEntity(self, Object=..., PickedPoint=..., Prompt=...): ...
    def GetInput(self): ...
    def GetInteger(self, Prompt=...): ...
    def GetKeyword(self, Prompt=...): ...
    def GetObjectIdString(self, Object=..., asHex=...): ...
    def GetOrientation(self, Point=..., Prompt=...): ...
    def GetPoint(self, Point=..., Prompt=...): ...
    def GetReal(self, Prompt=...): ...
    def GetRemoteFile(self, URL=..., LocalFile=..., IgnoreCache=...): ...
    def GetString(self, HasSpaces=..., Prompt=...): ...
    def GetSubEntity(self, Object=..., PickedPoint=..., transMatrix=..., ContextData=..., Prompt=...): ...
    def InitializeUserInput(self, Bits=..., KeyWordList=...): ...
    def IsRemoteFile(self, LocalFile=..., URL=...): ...
    def IsURL(self, URL=...): ...
    def LaunchBrowserDialog(self, SelectedURL=..., DialogTitle=..., OpenButtonCaption=..., StartPageURL=..., RegistryRootKey=..., OpenButtonAlwaysEnabled=...): ...
    def LogMessage(self, msg=...): ...
    def ObjectId32ToObjectIdString(self, objectId32=...): ...
    def PolarPoint(self, Point=..., Angle=..., Distance=...): ...
    def Prompt(self, Message=...): ...
    def PutRemoteFile(self, URL=..., LocalFile=...): ...
    def RealToString(self, Value=..., Unit=..., precision=...): ...
    def SendModelessOperationEnded(self, operation=...): ...
    def SendModelessOperationStart(self, operation=...): ...
    def TranslateCoordinates(self, Point=..., FromCoordSystem=..., ToCoordSystem=..., Displacement=..., OCSNormal=...): ...
    def __iter__(self): ...

class IOdaAuditInfo(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...

class IOdaBagFiler(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def BufferToObject(self, pObj=..., ResType=..., ResValue=...): ...
    def ObjectToBuffer(self, pObj=..., ResType=..., ResValue=...): ...
    def __iter__(self): ...

class IOdaBmpOut(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def WriteFile(self, database=..., BitmapName=...): ...
    def __iter__(self): ...

class IOdaConsole(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def GetString(self, bAllowSpaces=...): ...
    def PutString(self, text=...): ...
    def __iter__(self): ...

class IOdaDwf3dExport(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Export3dDwf(self, database=..., FileName=...): ...
    def __iter__(self): ...

class IOdaDwfImporter(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Import(self, database=..., FileName=..., Password: str = ..., wPaper: float = ..., hPaper: float = ...): ...
    def __iter__(self): ...

class IOdaDwfImporter2(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Close(self): ...
    def Import(self, database=..., FileName=..., Password: str = ..., wPaper: float = ..., hPaper: float = ...): ...
    def Properties(self, Name=...): ...
    def SetProperties(self, Name=..., arg1=...): ...
    def __iter__(self): ...

class IOdaDwfPageData(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...

class IOdaDwfTemplate(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def AddPage(self, LayoutName=...): ...
    def Page(self, Index=...): ...
    def RemoveAllPages(self): ...
    def RemovePage(self, Index=...): ...
    def WriteFile(self, database=..., FileName=..., FileType=..., version=...): ...
    def __iter__(self): ...

class IOdaHostApp(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def AuditDatabase(self, pDoc=..., bFixErrors=...): ...
    def BrowseForOpenFileName(self, rootFolder=..., fileFilter=..., bOk=..., FileName=...): ...
    def OriginalFileType(self, pDoc=..., FileType=...): ...
    def Recover(self, FileName=..., Password=...): ...
    def __iter__(self): ...

class IOdaHostApp2(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def AuditDatabase(self, pDoc=..., bFixErrors=...): ...
    def BrowseForOpenFileName(self, rootFolder=..., fileFilter=..., bOk=..., FileName=...): ...
    def OriginalFileType(self, pDoc=..., FileType=...): ...
    def Recover(self, FileName=..., Password=...): ...
    def __iter__(self): ...

class IOdaSvgExporter(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def Export(self, database=..., FilePath=...): ...
    def Properties(self, Name=...): ...
    def SetProperties(self, Name=..., arg1=...): ...
    def __iter__(self): ...

class ITransmittalFile(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def getDependee(self, nIndex=...): ...
    def getDependent(self, nIndex=...): ...
    def __iter__(self): ...

class ITransmittalFilesGraph(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def addEdge(self, pTransmitFileFrom=..., pTransmitFileTo=...): ...
    def getAt(self, nIndex=...): ...
    def getNumberOfFiles(self, bIncludeMissingFiles=..., bIncludeUnselectedFiles=...): ...
    def getRoot(self): ...
    def removeEdge(self, pTransmitFile=..., pParentFile=...): ...
    def reset(self): ...
    def totalBytes(self, bIncludedFilesOnly=...): ...
    def __iter__(self): ...

class ITransmittalInfo(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def __iter__(self): ...

class ITransmittalOperation(DispatchBaseClass):
    CLSID: Incomplete
    coclass_clsid: Incomplete
    def addDrawingFile(self, fullpathname=..., ppIAddedFile=...): ...
    def addFile(self, bstrFullPath=..., pIParentFile=..., bAddedBy3rdParty=..., ppIAddedFile=...): ...
    def addToReport(self, bstrTextToAdd=..., nIndex=...): ...
    def createTransmittalPackage(self): ...
    def getTransmittalGraphInterface(self): ...
    def getTransmittalInfoInterface(self): ...
    def getTransmittalReport(self): ...
    def __iter__(self): ...

class _DAcadApplicationEvents:
    CLSID: Incomplete
    CLSID_Sink: Incomplete
    coclass_clsid: Incomplete
    def __init__(self, oobj: Incomplete | None = ...) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...

class _DAcadDocumentEvents:
    CLSID: Incomplete
    CLSID_Sink: Incomplete
    coclass_clsid: Incomplete
    def __init__(self, oobj: Incomplete | None = ...) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...

class _IOdaHostAppEvents:
    CLSID: Incomplete
    CLSID_Sink: Incomplete
    coclass_clsid: Incomplete
    def __init__(self, oobj: Incomplete | None = ...) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...

class AcPePick2PointsCtrl(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete

class AcPePropertyEditorColor(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete

class AcPePropertyEditorEllipses(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete

class AcPePropertyEditorLType(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete

class AcPePropertyEditorLWeight(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete

class AcPePropertyEditorLayer(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete

class AcPePropertyEditorTextStyle(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete

class AcadApplication(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    default_source: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadApplication

class AcadDocument(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    default_source: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadDocument

class AcadDocuments(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadDocuments

class AcadLayerStateManager(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadLayerStateManager

class AcadMenuBar(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadMenuBar

class AcadMenuGroup(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadMenuGroup

class AcadMenuGroups(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadMenuGroups

class AcadPlot(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPlot

class AcadPopupMenu(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPopupMenu

class AcadPopupMenuItem(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPopupMenuItem

class AcadPopupMenus(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPopupMenus

class AcadPreferences(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferences

class AcadPreferencesDisplay(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesDisplay

class AcadPreferencesDrafting(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesDrafting

class AcadPreferencesFiles(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesFiles

class AcadPreferencesOpenSave(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesOpenSave

class AcadPreferencesOutput(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesOutput

class AcadPreferencesPdfOutput(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesPdfOutput

class AcadPreferencesProfiles(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesProfiles

class AcadPreferencesSelection(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesSelection

class AcadPreferencesSystem(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesSystem

class AcadPreferencesUser(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadPreferencesUser

class AcadSecurityParams(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadSecurityParams

class AcadSelectionSet(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadSelectionSet

class AcadSelectionSets(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadSelectionSets

class AcadState(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadState

class AcadToolbar(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadToolbar

class AcadToolbarItem(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadToolbarItem

class AcadToolbars(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadToolbars

class AcadUtility(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IAcadUtility

class OdaBagFiler(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IOdaBagFiler

class OdaBmpOut(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IOdaBmpOut

class OdaDwf3dExport(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IOdaDwf3dExport

class OdaDwfImporter(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IOdaDwfImporter

class OdaDwfTemplate(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IOdaDwfTemplate

class OdaHostApp(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    default_source: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IOdaHostApp2

class OdaSvgExporter(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = IOdaSvgExporter

class TransmittalFile(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = ITransmittalFile

class TransmittalFilesGraph(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = ITransmittalFilesGraph

class TransmittalInfo(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = ITransmittalInfo

class TransmittalOperation(CoClassBaseClass):
    CLSID: Incomplete
    coclass_sources: Incomplete
    coclass_interfaces: Incomplete
    default_interface = ITransmittalOperation

IAcadApplication_vtables_dispatch_: int
IAcadApplication_vtables_: Incomplete
IAcadDocument_vtables_dispatch_: int
IAcadDocument_vtables_: Incomplete
IAcadDocuments_vtables_dispatch_: int
IAcadDocuments_vtables_: Incomplete
IAcadLayerStateManager_vtables_dispatch_: int
IAcadLayerStateManager_vtables_: Incomplete
IAcadMenuBar_vtables_dispatch_: int
IAcadMenuBar_vtables_: Incomplete
IAcadMenuGroup_vtables_dispatch_: int
IAcadMenuGroup_vtables_: Incomplete
IAcadMenuGroups_vtables_dispatch_: int
IAcadMenuGroups_vtables_: Incomplete
IAcadPlot_vtables_dispatch_: int
IAcadPlot_vtables_: Incomplete
IAcadPopupMenu_vtables_dispatch_: int
IAcadPopupMenu_vtables_: Incomplete
IAcadPopupMenuItem_vtables_dispatch_: int
IAcadPopupMenuItem_vtables_: Incomplete
IAcadPopupMenus_vtables_dispatch_: int
IAcadPopupMenus_vtables_: Incomplete
IAcadPreferences_vtables_dispatch_: int
IAcadPreferences_vtables_: Incomplete
IAcadPreferencesDisplay_vtables_dispatch_: int
IAcadPreferencesDisplay_vtables_: Incomplete
IAcadPreferencesDrafting_vtables_dispatch_: int
IAcadPreferencesDrafting_vtables_: Incomplete
IAcadPreferencesFiles_vtables_dispatch_: int
IAcadPreferencesFiles_vtables_: Incomplete
IAcadPreferencesOpenSave_vtables_dispatch_: int
IAcadPreferencesOpenSave_vtables_: Incomplete
IAcadPreferencesOutput_vtables_dispatch_: int
IAcadPreferencesOutput_vtables_: Incomplete
IAcadPreferencesPdfOutput_vtables_dispatch_: int
IAcadPreferencesPdfOutput_vtables_: Incomplete
IAcadPreferencesProfiles_vtables_dispatch_: int
IAcadPreferencesProfiles_vtables_: Incomplete
IAcadPreferencesSelection_vtables_dispatch_: int
IAcadPreferencesSelection_vtables_: Incomplete
IAcadPreferencesSystem_vtables_dispatch_: int
IAcadPreferencesSystem_vtables_: Incomplete
IAcadPreferencesUser_vtables_dispatch_: int
IAcadPreferencesUser_vtables_: Incomplete
IAcadSecurityParams_vtables_dispatch_: int
IAcadSecurityParams_vtables_: Incomplete
IAcadSelectionSet_vtables_dispatch_: int
IAcadSelectionSet_vtables_: Incomplete
IAcadSelectionSets_vtables_dispatch_: int
IAcadSelectionSets_vtables_: Incomplete
IAcadState_vtables_dispatch_: int
IAcadState_vtables_: Incomplete
IAcadToolbar_vtables_dispatch_: int
IAcadToolbar_vtables_: Incomplete
IAcadToolbarItem_vtables_dispatch_: int
IAcadToolbarItem_vtables_: Incomplete
IAcadToolbars_vtables_dispatch_: int
IAcadToolbars_vtables_: Incomplete
IAcadUtility_vtables_dispatch_: int
IAcadUtility_vtables_: Incomplete
IOdaAuditInfo_vtables_dispatch_: int
IOdaAuditInfo_vtables_: Incomplete
IOdaBagFiler_vtables_dispatch_: int
IOdaBagFiler_vtables_: Incomplete
IOdaBmpOut_vtables_dispatch_: int
IOdaBmpOut_vtables_: Incomplete
IOdaConsole_vtables_dispatch_: int
IOdaConsole_vtables_: Incomplete
IOdaDwf3dExport_vtables_dispatch_: int
IOdaDwf3dExport_vtables_: Incomplete
IOdaDwfImporter_vtables_dispatch_: int
IOdaDwfImporter_vtables_: Incomplete
IOdaDwfImporter2_vtables_dispatch_: int
IOdaDwfImporter2_vtables_: Incomplete
IOdaDwfPageData_vtables_dispatch_: int
IOdaDwfPageData_vtables_: Incomplete
IOdaDwfTemplate_vtables_dispatch_: int
IOdaDwfTemplate_vtables_: Incomplete
IOdaHostApp_vtables_dispatch_: int
IOdaHostApp_vtables_: Incomplete
IOdaHostApp2_vtables_dispatch_: int
IOdaHostApp2_vtables_: Incomplete
IOdaSvgExporter_vtables_dispatch_: int
IOdaSvgExporter_vtables_: Incomplete
ITransmittalFile_vtables_dispatch_: int
ITransmittalFile_vtables_: Incomplete
ITransmittalFilesGraph_vtables_dispatch_: int
ITransmittalFilesGraph_vtables_: Incomplete
ITransmittalInfo_vtables_dispatch_: int
ITransmittalInfo_vtables_: Incomplete
ITransmittalOperation_vtables_dispatch_: int
ITransmittalOperation_vtables_: Incomplete
RecordMap: Incomplete
CLSIDToClassMap: Incomplete
CLSIDToPackageMap: Incomplete
VTablesToPackageMap: Incomplete
VTablesToClassMap: Incomplete
NamesToIIDMap: Incomplete
