#pragma once

#pragma pack (push, 8)
class PyDbObject;
class PyDbObjectId;
class PyDbEntity;
class PyGeCurve3d;
class PyDbCurve;
class PyDbDatabase;
class PyDbDatabaseSummaryInfo;
class PyDbSymUtilServices;
class PyDbTransactionManager;
class PyDbDimAssoc;

void makeDbCoreWrapper();

class DbCore
{
public:
    static PyDbObjectId         attachPointCloudExEntity(const std::string& pointCloudFile, AcGePoint3d& location, double scale, double rotation, PyDbDatabase& pDb);
    static boost::python::list  activeDatabaseArray();
    static double               angToF(const std::string& str, int unit);
    static std::string          angToS(double, int unit, int prec);
    static void                 assignGelibCurveToAcDbCurve1(const PyGeCurve3d& geCurve, PyDbCurve& pDbCurve);
    static void                 assignGelibCurveToAcDbCurve2(const PyGeCurve3d& geCurve, PyDbCurve& pDbCurve, AcGeVector3d& normal);
    static void                 assignGelibCurveToAcDbCurve3(const PyGeCurve3d& geCurve, PyDbCurve& pDbCurve, AcGeVector3d& normal, const AcGeTol& tol);
    static PyDbObjectId         attachXref(PyDbDatabase& pHostDb, const std::string& pFilename, const std::string& pBlockName);
    static void                 bindXrefs1(PyDbDatabase& pHostDb, const boost::python::list& xrefBlkIds, const bool bInsertBind);
    static void                 bindXrefs2(PyDbDatabase& pHostDb, const boost::python::list& xrefBlkIds, const bool bInsertBind, const bool bAllowUnresolved, const bool bQuiet);
    static void                 clearSetupForLayouts(UINT_PTR contextHandle);
    static PyGeCurve3d          convertAcDbCurveToGelibCurve1(const PyDbCurve& dbCurve);
    static PyGeCurve3d          convertAcDbCurveToGelibCurve2(const PyDbCurve& dbCurve, const AcGeTol& tol);
    static PyDbCurve            convertGelibCurveToAcDbCurve1(const PyGeCurve3d& geCurve);
    static PyDbCurve            convertGelibCurveToAcDbCurve2(const PyGeCurve3d& geCurve, AcGeVector3d& normal);
    static PyDbCurve            convertGelibCurveToAcDbCurve3(const PyGeCurve3d& geCurve, AcGeVector3d& normal, const AcGeTol& tol);
    static PyDbObjectId         createViewByViewport(PyDbDatabase& pDb, const PyDbObjectId& viewportId, const std::string& name, const std::string& categoryName, const PyDbObjectId& labelBlockId);
    static std::string          canonicalToSystemRange(int eUnits, const std::string& strIn);
    static void                 detachXref(PyDbDatabase& pHostDb, const PyDbObjectId& xrefBlkId);
    static bool                 dictAdd(const PyDbObjectId& dictname, const std::string& symname, const PyDbObjectId& newobj);
    static boost::python::list  dictNext(const PyDbObjectId& dictname, int rewind);
    static bool                 dictRemove(const PyDbObjectId& dictname, const std::string& symname);
    static bool                 dictRename(const PyDbObjectId& dictname, const std::string& symname, const std::string& newsym);
    static boost::python::list  dictSearch(const PyDbObjectId& dictname, const std::string& symname, int setnext);
    static bool                 displayPreviewFromDwg(const std::string& pszDwgfilename, UINT_PTR hwnd);
    static double               disToF(const std::string& str, int unit);
    static UINT_PTR             doSetupForLayouts(PyDbDatabase& pDatabase);
    static void                 dxfOutAs2000(PyDbDatabase& pDb, const std::string& fileName, int precision);
    static void                 dxfOutAs2004(PyDbDatabase& pDb, const std::string& fileName, int precision);
    static void                 dxfOutAsR12(PyDbDatabase& pDb, const std::string& fileName, int precision);
    static bool                 entMake(const boost::python::object& rb);
    static PyDbObjectId         entMakeX(const boost::python::object& rb);
    static bool                 entDel(const PyDbObjectId& id);
    static boost::python::list  entGet(const PyDbObjectId& id);
    static boost::python::list  entGetX1(const PyDbObjectId& id);
    static boost::python::list  entGetX2(const PyDbObjectId& id, const boost::python::list& rb);
    static PyDbObjectId         entLast();
    static bool                 entMod(const boost::python::list& list);
    static PyDbObjectId         entNext(const PyDbObjectId& id);
    static bool                 entUpd(const PyDbObjectId& id);
    static void                 fail(const std::string& msg);
    static boost::python::tuple findField(const std::string& pszText, int iSearchFrom);
    static void                 forceTextAdjust(const boost::python::list& ids);
    static PyDbObjectId         getCurUserViewportId(PyDbDatabase& db);
    static PyDbObjectId         getCurVportId(PyDbDatabase& db);
    static PyDbObjectId         getCurVportTableRecordId(PyDbDatabase& db);
    static PyDbObjectId         getDimAssocId(const PyDbObjectId& dimId);
    static boost::python::list  getDimAssocIds(const PyDbObjectId& id);
    static PyDbObjectId         getDimStyleId(PyDbDatabase& db, const std::string& styleName, const std::string& lockName);
    static PyDbObjectId         getDynDimStyleId(PyDbDatabase& db);
    static PyDbObjectId         getGeoDataObjId(PyDbDatabase& db);
    static bool                 hasGeoData(PyDbDatabase& db);
    static boost::python::tuple getProxyInfo(const PyDbObject& obj);
    static std::string          getMappedFontName(const std::string& fontName);
    static std::string          getReservedString(AcDb::reservedStringEnumType reservedType, bool bGetLocalized);
    static double               getUnitsConversion(AcDb::UnitsValue from, AcDb::UnitsValue to);
    static PyDbObjectId         getViewportVisualStyle();
    static PyDbObjectId         handEnt(const std::string& handle);
    static bool                 isEnabledTightExtents();
    static bool                 isReservedString(const std::string& strString, AcDb::reservedStringEnumType reservedType);
    static AcGePoint3d          inters(const AcGePoint3d& from1, const AcGePoint3d& to1, const AcGePoint3d& from2, const AcGePoint3d& to2, int teston);
    static void                 loadLineTypeFile(const std::string& ltname, const std::string& fname, PyDbDatabase& db);
    static void                 loadMlineStyleFile(const std::string& ltname, const std::string& fname);
    static PyDbObjectId         namedObjDict();
    static PyDbObject           openDbObject(const PyDbObjectId& id, AcDb::OpenMode mode, bool erased);
    static boost::python::list  openDbObjects1(const boost::python::list& ids);
    static boost::python::list  openDbObjects2(const boost::python::list& ids, AcDb::OpenMode mode);
    static boost::python::list  openDbObjects3(const boost::python::list& ids, AcDb::OpenMode mode, bool erased);
    static PyDbEntity           openDbEntity(const PyDbObjectId& id, AcDb::OpenMode mode, bool erased);
    static boost::python::list  openDbEntities1(const boost::python::list& ids);
    static boost::python::list  openDbEntities2(const boost::python::list& ids, AcDb::OpenMode mode);
    static boost::python::list  openDbEntities3(const boost::python::list& ids, AcDb::OpenMode mode, bool erased);
    static PyDbObjectId         postDimAssoc1(const PyDbObjectId& dimId, PyDbDimAssoc& assos);
    static PyDbObjectId         postDimAssoc2(const PyDbObjectId& dimId, PyDbDimAssoc& assos, bool isActive);
    static void                 queueAnnotationEntitiesForRegen(PyDbDatabase& db);
    static int                  queueForRegen(const boost::python::list& pyids);
    static bool                 regApp(const std::string& app);
    static std::string          rtos(double, int unit, int prec);
    static void                 updateDimension(const PyDbObjectId& id);
    static void                 reloadXrefs1(PyDbDatabase& db, const boost::python::list& ids);
    static void                 reloadXrefs2(PyDbDatabase& db, const boost::python::list& ids, bool bQuiet);
    static boost::python::list  resbufTest(const boost::python::list& list);
    static std::string          stringTest(const std::string& val);
    static std::string          stringtolower(const std::string& val);
    static std::string          stringtoupper(const std::string& val);
    static bool                 icompare(const std::string& left, const std::string& right);
    static void                 setEnableTightExtents(bool bEnable);
    static bool                 snValid(const std::string& tbstr, int pipeTest);
    static PyDbSymUtilServices  symUtil();
    static boost::python::list  tblNext(const std::string& tblname, int rewind);
    static PyDbObjectId         tblObjName(const std::string& tblname, const std::string& sym);
    static boost::python::list  tblSearch(const std::string& tblname, const std::string& sym, int setnext);
    static boost::python::list  textFind1(PyDbDatabase& db, const std::string& findString);
    static boost::python::list  textFind2(PyDbDatabase& db, const std::string& findString, const std::string& replaceString, Adesk::UInt8 searchOptions, const boost::python::list& selSet);
    static PyDbTransactionManager transactionManager();
    static AcGeMatrix3d         ucsMatrix1();
    static AcGeMatrix3d         ucsMatrix2(PyDbDatabase& db);
    static void                 unloadXrefs1(PyDbDatabase& db, const boost::python::list& xrefBlkIds);
    static void                 unloadXrefs2(PyDbDatabase& db, const boost::python::list& xrefBlkIds, bool bQuiet);
    static PyDbDatabaseSummaryInfo getSummaryInfo(PyDbDatabase& db);
    static void                 putSummaryInfo(PyDbDatabaseSummaryInfo& info, PyDbDatabase& db);
    static bool                 validateCustomSummaryInfoKey(const std::string& key, PyDbDatabaseSummaryInfo& info);
    static bool                 ucs2Wcs1(const AcGePoint3d& p, AcGePoint3d& q);
    static bool                 ucs2Wcs2(const AcGeVector3d& p, AcGeVector3d& q);
    static bool                 wcs2Ecs1(const AcGePoint3d& p, const AcGeVector3d& normal, AcGePoint3d& q);
    static bool                 wcs2Ecs2(const AcGeVector3d& p, const AcGeVector3d& normal, AcGeVector3d& q);
    static bool                 wcs2Ucs1(const AcGePoint3d& p, AcGePoint3d& q);
    static bool                 wcs2Ucs2(const AcGeVector3d& p, AcGeVector3d& q);
    static bool                 ecs2Wcs1(const AcGePoint3d& p, const AcGeVector3d& normal, AcGePoint3d& q);
    static bool                 ecs2Wcs2(const AcGeVector3d& p, const AcGeVector3d& normal, AcGeVector3d& q);
    static Acad::ErrorStatus    evaluateFields1();
    static Acad::ErrorStatus    evaluateFields2(const boost::python::object& ids, int context);
    static void                 resolveCurrentXRefs(const PyDbDatabase& db, bool useThreadEngine, bool doNewOnly);
};

#pragma pack (pop)
