#pragma once
#include "PyAcadEntityImpl.h"

//------------------------------------------------------------------------------------
//PyIAcadDimensionImpl
class PyIAcadDimensionImpl : public PyIAcadEntityImpl
{
public:
    explicit PyIAcadDimensionImpl(IAcadDimension* ptr);
    virtual ~PyIAcadDimensionImpl() override = default;

    AcGeVector3d                    GetNormal() const;
    void                            SetNormal(const AcGeVector3d& val) const;
    double                          GetRotation() const;
    void                            SetRotation(double val) const;
    AcGePoint3d                     GetTextPosition() const;
    void                            SetTextPosition(const AcGePoint3d& val) const;
    double                          GetTextRotation() const;
    void                            SetTextRotation(double val) const;
    CString                         GetTextOverride() const;
    void                            SetTextOverride(const CString& val) const;
    CString                         GetStyleName() const;
    void                            SetStyleName(const CString& val) const;
    PyAcColor                       GetTextColor() const;
    void                            SetTextColor(PyAcColor val) const;
    CString                         GetDecimalSeparator() const;
    void                            SetDecimalSeparator(const CString& val) const;
    double                          GetTextGap() const;
    void                            SetTextGap(double val) const;
    CString                         GetTextPrefix() const;
    void                            SetTextPrefix(const CString& val) const;
    CString                         GetTextSuffix() const;
    void                            SetTextSuffix(const CString& val) const;
    double                          GetScaleFactor() const;
    void                            SetScaleFactor(double val) const;
    PyAcDimVerticalJustification    GetVerticalTextPosition() const;
    void                            SetVerticalTextPosition(PyAcDimVerticalJustification val) const;
    PyAcDimPrecision                GetTolerancePrecision() const;
    void                            SetTolerancePrecision(PyAcDimPrecision val) const;
    double                          GetToleranceHeightScale() const;
    void                            SetToleranceHeightScale(double val) const;
    double                          GetToleranceLowerLimit() const;
    void                            SetToleranceLowerLimit(double val) const;
    PyAcDimTextMovement             GetTextMovement() const;
    void                            SetTextMovement(PyAcDimTextMovement val) const;
    PyAcDimToleranceMethod          GetToleranceDisplay() const;
    void                            SetToleranceDisplay(PyAcDimToleranceMethod val) const;
    PyAcDimToleranceJustify         GetToleranceJustification() const;
    void                            SetToleranceJustification(PyAcDimToleranceJustify val) const;
    double                          GetToleranceUpperLimit() const;
    void                            SetToleranceUpperLimit(double val) const;
    CString                         GetTextStyle() const;
    void                            SetTextStyle(const CString& val) const;
    double                          GetTextHeight() const;
    void                            SetTextHeight(double val) const;
    bool                            GetSuppressLeadingZeros() const;
    void                            SetSuppressLeadingZeros(bool val) const;
    bool                            GetSuppressTrailingZeros() const;
    void                            SetSuppressTrailingZeros(bool val) const;
    bool                            GetToleranceSuppressLeadingZeros() const;
    void                            SetToleranceSuppressLeadingZeros(bool val) const;
    bool                            GetToleranceSuppressTrailingZeros() const;
    void                            SetToleranceSuppressTrailingZeros(bool val) const;
    bool                            GetTextFill() const;
    void                            SetTextFill(bool val) const;
    PyAcColor                       GetTextFillColor() const;
    void                            SetTextFillColor(PyAcColor val) const;
    bool                            GetDimTxtDirection() const;
    void                            SetDimTxtDirection(bool val) const;

    IAcadDimension* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDimensionPtr = std::unique_ptr<PyIAcadDimensionImpl>;

//------------------------------------------------------------------------------------
//PyIAcadDimAlignedImpl
class PyIAcadDimAlignedImpl : public PyIAcadDimensionImpl
{
public:
    explicit PyIAcadDimAlignedImpl(IAcadDimAligned* ptr);
    virtual ~PyIAcadDimAlignedImpl() override = default;

    AcGePoint3d             GetExtLine1Point() const;
    void                    SetExtLine1Point(const AcGePoint3d& val) const;
    AcGePoint3d             GetExtLine2Point() const;
    void                    SetExtLine2Point(const AcGePoint3d& val) const;
    bool                    GetAltUnits() const;
    void                    SetAltUnits(bool val) const;
    PyAcDimPrecision        GetAltUnitsPrecision() const;
    void                    SetAltUnitsPrecision(PyAcDimPrecision val) const;
    double                  GetAltUnitsScale() const;
    void                    SetAltUnitsScale(double val) const;
    double                  GetAltRoundDistance() const;
    void                    SetAltRoundDistance(double val) const;
    PyAcDimPrecision        GetAltTolerancePrecision() const;
    void                    SetAltTolerancePrecision(PyAcDimPrecision val) const;
    PyAcDimUnits            GetAltUnitsFormat() const;
    void                    SetAltUnitsFormat(PyAcDimUnits val) const;
    CString                 GetAltTextPrefix() const;
    void                    SetAltTextPrefix(const CString& val) const;
    CString                 GetAltTextSuffix() const;
    void                    SetAltTextSuffix(const CString& val) const;
    PyAcColor               GetDimensionLineColor() const;
    void                    SetDimensionLineColor(PyAcColor val) const;
    PyAcColor               GetExtensionLineColor() const;
    void                    SetExtensionLineColor(PyAcColor val) const;
    PyAcDimPrecision        GetPrimaryUnitsPrecision() const;
    void                    SetPrimaryUnitsPrecision(PyAcDimPrecision val) const;
    double                  GetDimensionLineExtend() const;
    void                    SetDimensionLineExtend(double val) const;
    double                  GetExtensionLineExtend() const;
    void                    SetExtensionLineExtend(double val) const;
    PyAcDimFit              GetFit() const;
    void                    SetFit(PyAcDimFit val) const;
    PyAcDimFractionType     GetFractionFormat() const;
    void                    SetFractionFormat(PyAcDimFractionType val) const;
    PyAcDimHorizontalJustification     GetHorizontalTextPosition() const;
    void                               SetHorizontalTextPosition(PyAcDimHorizontalJustification val) const;
    double                  GetLinearScaleFactor() const;
    void                    SetLinearScaleFactor(double val) const;
    PyAcDimLUnits           GetUnitsFormat() const;
    void                    SetUnitsFormat(PyAcDimLUnits val) const;
    PyAcLineWeight          GetExtensionLineWeight() const;
    void                    SetExtensionLineWeight(PyAcLineWeight val) const;
    double                  GetRoundDistance() const;
    void                    SetRoundDistance(double val) const;
    bool                    GetDimLine1Suppress() const;
    void                    SetDimLine1Suppress(bool val) const;
    bool                    GetDimLine2Suppress() const;
    void                    SetDimLine2Suppress(bool val) const;
    bool                    GetExtLine1Suppress() const;
    void                    SetExtLine1Suppress(bool val) const;
    bool                    GetExtLine2Suppress() const;
    void                    SetExtLine2Suppress(bool val) const;
    bool                    GetDimLineInside() const;
    void                    SetDimLineInside(bool val) const;
    bool                    GetTextInsideAlign() const;
    void                    SetTextInsideAlign(bool val) const;
    bool                    GetTextInside() const;
    void                    SetTextInside(bool val) const;
    bool                    GetForceLineInside() const;
    void                    SetForceLineInside(bool val) const;
    bool                    GetTextOutsideAlign() const;
    void                    SetTextOutsideAlign(bool val) const;
    double                  GetExtensionLineOffset() const;
    void                    SetExtensionLineOffset(double val) const;
    bool                    GetAltSuppressLeadingZeros() const;
    void                    SetAltSuppressLeadingZeros(bool val) const;
    bool                    GetAltSuppressTrailingZeros() const;
    void                    SetAltSuppressTrailingZeros(bool val) const;
    bool                    GetAltSuppressZeroFeet() const;
    void                    SetAltSuppressZeroFeet(bool val) const;
    bool                    GetAltSuppressZeroInches() const;
    void                    SetAltSuppressZeroInches(bool val) const;
    bool                    GetAltToleranceSuppressLeadingZeros() const;
    void                    SetAltToleranceSuppressLeadingZeros(bool val) const;
    bool                    GetAltToleranceSuppressTrailingZeros() const;
    void                    SetAltToleranceSuppressTrailingZeros(bool val) const;
    bool                    GetAltToleranceSuppressZeroFeet() const;
    void                    SetAltToleranceSuppressZeroFeet(bool val) const;
    bool                    GetAltToleranceSuppressZeroInches() const;
    void                    SetAltToleranceSuppressZeroInches(bool val) const;
    bool                    GetSuppressZeroFeet() const;
    void                    SetSuppressZeroFeet(bool val) const;
    bool                    GetSuppressZeroInches() const;
    void                    SetSuppressZeroInches(bool val) const;
    bool                    GetToleranceSuppressZeroFeet() const;
    void                    SetToleranceSuppressZeroFeet(bool val) const;
    bool                    GetToleranceSuppressZeroInches() const;
    void                    SetToleranceSuppressZeroInches(bool val) const;
    PyAcLineWeight          GetDimensionLineWeight() const;
    void                    SetDimensionLineWeight(PyAcLineWeight val) const;
    double                  GetArrowheadSize() const;
    void                    SetArrowheadSize(double val) const;
    PyAcDimArrowheadType    GetArrowhead1Type() const;
    void                    SetArrowhead1Type(PyAcDimArrowheadType val) const;
    PyAcDimArrowheadType    GetArrowhead2Type() const;
    void                    SetArrowhead2Type(PyAcDimArrowheadType val) const;
    double                  GetMeasurement() const;
    CString                 GetArrowhead1Block() const;
    void                    SetArrowhead1Block(const CString& val) const;
    CString                 GetArrowhead2Block() const;
    void                    SetArrowhead2Block(const CString& val) const;
    CString                 GetDimensionLinetype() const;
    void                    SetDimensionLinetype(const CString& val) const;
    CString                 GetExtLine1Linetype() const;
    void                    SetExtLine1Linetype(const CString& val) const;
    CString                 GetExtLine2Linetype() const;
    void                    SetExtLine2Linetype(const CString& val) const;
    bool                    GetExtLineFixedLenSuppress() const;
    void                    SetExtLineFixedLenSuppress(bool val) const;
    double                  GetExtLineFixedLen() const;
    void                    SetExtLineFixedLen(double val) const;
    bool                    GetDimConstrForm() const;
    void                    SetDimConstrForm(bool val) const;
    bool                    GetDimConstrReference() const;
    void                    SetDimConstrReference(bool val) const;
    CString                 GetDimConstrName() const;
    void                    SetDimConstrName(const CString& val) const;
    CString                 GetDimConstrExpression() const;
    void                    SetDimConstrExpression(const CString& val) const;
    CString                 GetDimConstrValue() const;
    void                    SetDimConstrValue(const CString& val) const;
    CString                 GetDimConstrDesc() const;
    void                    SetDimConstrDesc(const CString& val) const;
    CString                 GetSubUnitsSuffix() const;
    void                    SetSubUnitsSuffix(const CString& val) const;
    double                  GetSubUnitsFactor() const;
    void                    SetSubUnitsFactor(double val) const;
    CString                 GetAltSubUnitsSuffix() const;
    void                    SetAltSubUnitsSuffix(const CString& val) const;
    double                  GetAltSubUnitsFactor() const;
    void                    SetAltSubUnitsFactor(double val) const;

    IAcadDimAligned* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDimAlignedPtr = std::unique_ptr<PyIAcadDimAlignedImpl>;

//------------------------------------------------------------------------------------
//PyIAcadDimAngularImpl
class PyIAcadDimAngularImpl : public PyIAcadDimensionImpl
{
public:
    explicit PyIAcadDimAngularImpl(IAcadDimAngular* ptr);
    virtual ~PyIAcadDimAngularImpl() override = default;

    AcGePoint3d             GetExtLine1StartPoint() const;
    void                    SetExtLine1StartPoint(const AcGePoint3d& val) const;
    AcGePoint3d             GetExtLine1EndPoint() const;
    void                    SetExtLine1EndPoint(const AcGePoint3d& val) const;
    AcGePoint3d             GetExtLine2StartPoint() const;
    void                    SetExtLine2StartPoint(const AcGePoint3d& val) const;
    AcGePoint3d             GetExtLine2EndPoint() const;
    void                    SetExtLine2EndPoint(const AcGePoint3d& val) const;
    PyAcAngleUnits          GetAngleFormat() const;
    void                    SetAngleFormat(PyAcAngleUnits val) const;
    PyAcColor               GetDimensionLineColor() const;
    void                    SetDimensionLineColor(PyAcColor val) const;
    PyAcColor               GetExtensionLineColor() const;
    void                    SetExtensionLineColor(PyAcColor val) const;
    double                  GetExtensionLineExtend() const;
    void                    SetExtensionLineExtend(double val) const;
    PyAcDimFit              GetFit() const;
    void                    SetFit(PyAcDimFit val) const;
    PyAcDimHorizontalJustification     GetHorizontalTextPosition() const;
    void                               SetHorizontalTextPosition(PyAcDimHorizontalJustification val) const;
    PyAcLineWeight          GetExtensionLineWeight() const;
    void                    SetExtensionLineWeight(PyAcLineWeight val) const;
    bool                    GetDimLine1Suppress() const;
    void                    SetDimLine1Suppress(bool val) const;
    bool                    GetDimLine2Suppress() const;
    void                    SetDimLine2Suppress(bool val) const;
    bool                    GetExtLine1Suppress() const;
    void                    SetExtLine1Suppress(bool val) const;
    bool                    GetExtLine2Suppress() const;
    void                    SetExtLine2Suppress(bool val) const;
    bool                    GetDimLineInside() const;
    void                    SetDimLineInside(bool val) const;
    bool                    GetTextInsideAlign() const;
    void                    SetTextInsideAlign(bool val) const;
    bool                    GetTextInside() const;
    void                    SetTextInside(bool val) const;
    bool                    GetForceLineInside() const;
    void                    SetForceLineInside(bool val) const;
    bool                    GetTextOutsideAlign() const;
    void                    SetTextOutsideAlign(bool val) const;
    PyAcDimPrecision        GetTextPrecision() const;
    void                    SetTextPrecision(PyAcDimPrecision val) const;
    double                  GetExtensionLineOffset() const;
    void                    SetExtensionLineOffset(double val) const;
    PyAcLineWeight          GetDimensionLineWeight() const;
    void                    SetDimensionLineWeight(PyAcLineWeight val) const;
    double                  GetArrowheadSize() const;
    void                    SetArrowheadSize(double val) const;
    PyAcDimArrowheadType    GetArrowhead1Type() const;
    void                    SetArrowhead1Type(PyAcDimArrowheadType val) const;
    PyAcDimArrowheadType    GetArrowhead2Type() const;
    void                    SetArrowhead2Type(PyAcDimArrowheadType val) const;
    double                  GetMeasurement() const;
    CString                 GetArrowhead1Block() const;
    void                    SetArrowhead1Block(const CString& val) const;
    CString                 GetArrowhead2Block() const;
    void                    SetArrowhead2Block(const CString& val) const;
    CString                 GetDimensionLinetype() const;
    void                    SetDimensionLinetype(const CString& val) const;
    CString                 GetExtLine1Linetype() const;
    void                    SetExtLine1Linetype(const CString& val) const;
    CString                 GetExtLine2Linetype() const;
    void                    SetExtLine2Linetype(const CString& val) const;
    bool                    GetExtLineFixedLenSuppress() const;
    void                    SetExtLineFixedLenSuppress(bool val) const;
    double                  GetExtLineFixedLen() const;
    void                    SetExtLineFixedLen(double val) const;
    bool                    GetDimConstrForm() const;
    void                    SetDimConstrForm(bool val) const;
    bool                    GetDimConstrReference() const;
    void                    SetDimConstrReference(bool val) const;
    CString                 GetDimConstrName() const;
    void                    SetDimConstrName(const CString& val) const;
    CString                 GetDimConstrExpression() const;
    void                    SetDimConstrExpression(const CString& val) const;
    CString                 GetDimConstrValue() const;
    void                    SetDimConstrValue(const CString& val) const;
    CString                 GetDimConstrDesc() const;
    void                    SetDimConstrDesc(const CString& val) const;

    IAcadDimAngular* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDimAngularPtr = std::unique_ptr<PyIAcadDimAngularImpl>;

//------------------------------------------------------------------------------------
//PyIAcadDimDiametricImpl
class PyIAcadDimDiametricImpl : public PyIAcadDimensionImpl
{
public:
    explicit PyIAcadDimDiametricImpl(IAcadDimDiametric* ptr);
    virtual ~PyIAcadDimDiametricImpl() override = default;
    void                    SetLeaderLength(double val) const;
    bool                    GetAltUnits() const;
    void                    SetAltUnits(bool val) const;
    PyAcDimPrecision        GetAltUnitsPrecision() const;
    void                    SetAltUnitsPrecision(PyAcDimPrecision val) const;
    double                  GetAltUnitsScale() const;
    void                    SetAltUnitsScale(double val) const;
    PyAcDimPrecision        GetAltTolerancePrecision() const;
    void                    SetAltTolerancePrecision(PyAcDimPrecision val) const;
    PyAcDimUnits            GetAltUnitsFormat() const;
    void                    SetAltUnitsFormat(PyAcDimUnits val) const;
    CString                 GetAltTextPrefix() const;
    void                    SetAltTextPrefix(const CString& val) const;
    CString                 GetAltTextSuffix() const;
    void                    SetAltTextSuffix(const CString& val) const;
    PyAcColor               GetDimensionLineColor() const;
    void                    SetDimensionLineColor(PyAcColor val) const;
    PyAcDimPrecision        GetPrimaryUnitsPrecision() const;
    void                    SetPrimaryUnitsPrecision(PyAcDimPrecision val) const;
    PyAcDimFractionType     GetFractionFormat() const;
    void                    SetFractionFormat(PyAcDimFractionType val) const;
    PyAcDimFit              GetFit() const;
    void                    SetFit(PyAcDimFit val) const;
    double                  GetLinearScaleFactor() const;
    void                    SetLinearScaleFactor(double val) const;
    PyAcDimLUnits           GetUnitsFormat() const;
    void                    SetUnitsFormat(PyAcDimLUnits val) const;
    double                  GetRoundDistance() const;
    void                    SetRoundDistance(double val) const;
    bool                    GetDimLine1Suppress() const;
    void                    SetDimLine1Suppress(bool val) const;
    bool                    GetDimLine2Suppress() const;
    void                    SetDimLine2Suppress(bool val) const;
    bool                    GetTextInsideAlign() const;
    void                    SetTextInsideAlign(bool val) const;
    bool                    GetTextInside() const;
    void                    SetTextInside(bool val) const;
    bool                    GetForceLineInside() const;
    void                    SetForceLineInside(bool val) const;
    bool                    GetTextOutsideAlign() const;
    void                    SetTextOutsideAlign(bool val) const;
    PyAcDimCenterType       GetCenterType() const;
    void                    SetCenterType(PyAcDimCenterType val) const;
    double                  GetCenterMarkSize() const;
    void                    SetCenterMarkSize(double val) const;
    bool                    GetAltSuppressLeadingZeros() const;
    void                    SetAltSuppressLeadingZeros(bool val) const;
    bool                    GetAltSuppressTrailingZeros() const;
    void                    SetAltSuppressTrailingZeros(bool val) const;
    bool                    GetAltSuppressZeroFeet() const;
    void                    SetAltSuppressZeroFeet(bool val) const;
    bool                    GetAltSuppressZeroInches() const;
    void                    SetAltSuppressZeroInches(bool val) const;
    bool                    GetAltToleranceSuppressLeadingZeros() const;
    void                    SetAltToleranceSuppressLeadingZeros(bool val) const;
    bool                    GetAltToleranceSuppressTrailingZeros() const;
    void                    SetAltToleranceSuppressTrailingZeros(bool val) const;
    bool                    GetAltToleranceSuppressZeroFeet() const;
    void                    SetAltToleranceSuppressZeroFeet(bool val) const;
    bool                    GetAltToleranceSuppressZeroInches() const;
    void                    SetAltToleranceSuppressZeroInches(bool val) const;
    bool                    GetSuppressZeroFeet() const;
    void                    SetSuppressZeroFeet(bool val) const;
    bool                    GetSuppressZeroInches() const;
    void                    SetSuppressZeroInches(bool val) const;
    bool                    GetToleranceSuppressZeroFeet() const;
    void                    SetToleranceSuppressZeroFeet(bool val) const;
    bool                    GetToleranceSuppressZeroInches() const;
    void                    SetToleranceSuppressZeroInches(bool val) const;
    PyAcLineWeight          GetDimensionLineWeight() const;
    void                    SetDimensionLineWeight(PyAcLineWeight val) const;
    double                  GetArrowheadSize() const;
    void                    SetArrowheadSize(double val) const;
    PyAcDimArrowheadType    GetArrowhead1Type() const;
    void                    SetArrowhead1Type(PyAcDimArrowheadType val) const;
    PyAcDimArrowheadType    GetArrowhead2Type() const;
    void                    SetArrowhead2Type(PyAcDimArrowheadType val) const;
    double                  GetMeasurement() const;
    CString                 GetArrowhead1Block() const;
    void                    SetArrowhead1Block(const CString& val) const;
    CString                 GetArrowhead2Block() const;
    void                    SetArrowhead2Block(const CString& val) const;
    CString                 GetDimensionLinetype() const;
    void                    SetDimensionLinetype(const CString& val) const;
    bool                    GetDimConstrForm() const;
    void                    SetDimConstrForm(bool val) const;
    bool                    GetDimConstrReference() const;
    void                    SetDimConstrReference(bool val) const;
    CString                 GetDimConstrName() const;
    void                    SetDimConstrName(const CString& val) const;
    CString                 GetDimConstrExpression() const;
    void                    SetDimConstrExpression(const CString& val) const;
    CString                 GetDimConstrValue() const;
    void                    SetDimConstrValue(const CString& val) const;
    CString                 GetDimConstrDesc() const;
    void                    SetDimConstrDesc(const CString& val) const;

    IAcadDimDiametric* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDimDiametricPtr = std::unique_ptr<PyIAcadDimDiametricImpl>;

//------------------------------------------------------------------------------------
//PyIAcadDimRotatedImpl
class PyIAcadDimRotatedImpl : public PyIAcadDimensionImpl
{
public:
    explicit PyIAcadDimRotatedImpl(IAcadDimRotated* ptr);
    virtual ~PyIAcadDimRotatedImpl() override = default;

    bool                    GetAltUnits() const;
    void                    SetAltUnits(bool val) const;
    PyAcDimPrecision        GetAltUnitsPrecision() const;
    void                    SetAltUnitsPrecision(PyAcDimPrecision val) const;
    double                  GetAltUnitsScale() const;
    void                    SetAltUnitsScale(double val) const;
    double                  GetAltRoundDistance() const;
    void                    SetAltRoundDistance(double val) const;
    PyAcDimPrecision        GetAltTolerancePrecision() const;
    void                    SetAltTolerancePrecision(PyAcDimPrecision val) const;
    PyAcDimUnits            GetAltUnitsFormat() const;
    void                    SetAltUnitsFormat(PyAcDimUnits val) const;
    CString                 GetAltTextPrefix() const;
    void                    SetAltTextPrefix(const CString& val) const;
    CString                 GetAltTextSuffix() const;
    void                    SetAltTextSuffix(const CString& val) const;
    PyAcColor               GetDimensionLineColor() const;
    void                    SetDimensionLineColor(PyAcColor val) const;
    PyAcColor               GetExtensionLineColor() const;
    void                    SetExtensionLineColor(PyAcColor val) const;
    PyAcDimPrecision        GetPrimaryUnitsPrecision() const;
    void                    SetPrimaryUnitsPrecision(PyAcDimPrecision val) const;
    double                  GetDimensionLineExtend() const;
    void                    SetDimensionLineExtend(double val) const;
    double                  GetExtensionLineExtend() const;
    void                    SetExtensionLineExtend(double val) const;
    PyAcDimFit              GetFit() const;
    void                    SetFit(PyAcDimFit val) const;
    PyAcDimFractionType     GetFractionFormat() const;
    void                    SetFractionFormat(PyAcDimFractionType val) const;
    PyAcDimHorizontalJustification     GetHorizontalTextPosition() const;
    void                               SetHorizontalTextPosition(PyAcDimHorizontalJustification val) const;
    double                  GetLinearScaleFactor() const;
    void                    SetLinearScaleFactor(double val) const;
    PyAcDimLUnits           GetUnitsFormat() const;
    void                    SetUnitsFormat(PyAcDimLUnits val) const;
    PyAcLineWeight          GetExtensionLineWeight() const;
    void                    SetExtensionLineWeight(PyAcLineWeight val) const;
    double                  GetRoundDistance() const;
    void                    SetRoundDistance(double val) const;
    bool                    GetDimLine1Suppress() const;
    void                    SetDimLine1Suppress(bool val) const;
    bool                    GetDimLine2Suppress() const;
    void                    SetDimLine2Suppress(bool val) const;
    bool                    GetExtLine1Suppress() const;
    void                    SetExtLine1Suppress(bool val) const;
    bool                    GetExtLine2Suppress() const;
    void                    SetExtLine2Suppress(bool val) const;
    bool                    GetDimLineInside() const;
    void                    SetDimLineInside(bool val) const;
    bool                    GetTextInsideAlign() const;
    void                    SetTextInsideAlign(bool val) const;
    bool                    GetTextInside() const;
    void                    SetTextInside(bool val) const;
    bool                    GetForceLineInside() const;
    void                    SetForceLineInside(bool val) const;
    bool                    GetTextOutsideAlign() const;
    void                    SetTextOutsideAlign(bool val) const;
    double                  GetExtensionLineOffset() const;
    void                    SetExtensionLineOffset(double val) const;
    bool                    GetAltSuppressLeadingZeros() const;
    void                    SetAltSuppressLeadingZeros(bool val) const;
    bool                    GetAltSuppressTrailingZeros() const;
    void                    SetAltSuppressTrailingZeros(bool val) const;
    bool                    GetAltSuppressZeroFeet() const;
    void                    SetAltSuppressZeroFeet(bool val) const;
    bool                    GetAltSuppressZeroInches() const;
    void                    SetAltSuppressZeroInches(bool val) const;
    bool                    GetAltToleranceSuppressLeadingZeros() const;
    void                    SetAltToleranceSuppressLeadingZeros(bool val) const;
    bool                    GetAltToleranceSuppressTrailingZeros() const;
    void                    SetAltToleranceSuppressTrailingZeros(bool val) const;
    bool                    GetAltToleranceSuppressZeroFeet() const;
    void                    SetAltToleranceSuppressZeroFeet(bool val) const;
    bool                    GetAltToleranceSuppressZeroInches() const;
    void                    SetAltToleranceSuppressZeroInches(bool val) const;
    bool                    GetSuppressZeroFeet() const;
    void                    SetSuppressZeroFeet(bool val) const;
    bool                    GetSuppressZeroInches() const;
    void                    SetSuppressZeroInches(bool val) const;
    bool                    GetToleranceSuppressZeroFeet() const;
    void                    SetToleranceSuppressZeroFeet(bool val) const;
    bool                    GetToleranceSuppressZeroInches() const;
    void                    SetToleranceSuppressZeroInches(bool val) const;
    PyAcLineWeight          GetDimensionLineWeight() const;
    void                    SetDimensionLineWeight(PyAcLineWeight val) const;
    double                  GetArrowheadSize() const;
    void                    SetArrowheadSize(double val) const;
    PyAcDimArrowheadType    GetArrowhead1Type() const;
    void                    SetArrowhead1Type(PyAcDimArrowheadType val) const;
    PyAcDimArrowheadType    GetArrowhead2Type() const;
    void                    SetArrowhead2Type(PyAcDimArrowheadType val) const;
    double                  GetMeasurement() const;
    CString                 GetArrowhead1Block() const;
    void                    SetArrowhead1Block(const CString& val) const;
    CString                 GetArrowhead2Block() const;
    void                    SetArrowhead2Block(const CString& val) const;
    CString                 GetDimensionLinetype() const;
    void                    SetDimensionLinetype(const CString& val) const;
    CString                 GetExtLine1Linetype() const;
    void                    SetExtLine1Linetype(const CString& val) const;
    CString                 GetExtLine2Linetype() const;
    void                    SetExtLine2Linetype(const CString& val) const;
    bool                    GetExtLineFixedLenSuppress() const;
    void                    SetExtLineFixedLenSuppress(bool val) const;
    double                  GetExtLineFixedLen() const;
    void                    SetExtLineFixedLen(double val) const;
    bool                    GetDimConstrForm() const;
    void                    SetDimConstrForm(bool val) const;
    bool                    GetDimConstrReference() const;
    void                    SetDimConstrReference(bool val) const;
    CString                 GetDimConstrName() const;
    void                    SetDimConstrName(const CString& val) const;
    CString                 GetDimConstrExpression() const;
    void                    SetDimConstrExpression(const CString& val) const;
    CString                 GetDimConstrValue() const;
    void                    SetDimConstrValue(const CString& val) const;
    CString                 GetDimConstrDesc() const;
    void                    SetDimConstrDesc(const CString& val) const;
    CString                 GetSubUnitsSuffix() const;
    void                    SetSubUnitsSuffix(const CString& val) const;
    double                  GetSubUnitsFactor() const;
    void                    SetSubUnitsFactor(double val) const;
    CString                 GetAltSubUnitsSuffix() const;
    void                    SetAltSubUnitsSuffix(const CString& val) const;
    double                  GetAltSubUnitsFactor() const;
    void                    SetAltSubUnitsFactor(double val) const;

    IAcadDimRotated* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDimRotatedPtr = std::unique_ptr<PyIAcadDimRotatedImpl>;

//------------------------------------------------------------------------------------
//PyIAcadDimOrdinateImpl
class PyIAcadDimOrdinateImpl : public PyIAcadDimensionImpl
{
public:
    explicit PyIAcadDimOrdinateImpl(IAcadDimOrdinate* ptr);
    virtual ~PyIAcadDimOrdinateImpl() override = default;

    bool                    GetAltUnits() const;
    void                    SetAltUnits(bool val) const;
    PyAcDimPrecision        GetAltUnitsPrecision() const;
    void                    SetAltUnitsPrecision(PyAcDimPrecision val) const;
    double                  GetAltUnitsScale() const;
    void                    SetAltUnitsScale(double val) const;
    double                  GetAltRoundDistance() const;
    void                    SetAltRoundDistance(double val) const;
    PyAcDimPrecision        GetAltTolerancePrecision() const;
    void                    SetAltTolerancePrecision(PyAcDimPrecision val) const;
    PyAcDimUnits            GetAltUnitsFormat() const;
    void                    SetAltUnitsFormat(PyAcDimUnits val) const;
    CString                 GetAltTextPrefix() const;
    void                    SetAltTextPrefix(const CString& val) const;
    CString                 GetAltTextSuffix() const;
    void                    SetAltTextSuffix(const CString& val) const;
    PyAcColor               GetExtensionLineColor() const;
    void                    SetExtensionLineColor(PyAcColor val) const;
    PyAcDimPrecision        GetPrimaryUnitsPrecision() const;
    void                    SetPrimaryUnitsPrecision(PyAcDimPrecision val) const;
    PyAcDimFractionType     GetFractionFormat() const;
    void                    SetFractionFormat(PyAcDimFractionType val) const;
    double                  GetLinearScaleFactor() const;
    void                    SetLinearScaleFactor(double val) const;
    PyAcDimLUnits           GetUnitsFormat() const;
    void                    SetUnitsFormat(PyAcDimLUnits val) const;
    PyAcLineWeight          GetExtensionLineWeight() const;
    void                    SetExtensionLineWeight(PyAcLineWeight val) const;
    double                  GetRoundDistance() const;
    void                    SetRoundDistance(double val) const;
    double                  GetExtensionLineOffset() const;
    void                    SetExtensionLineOffset(double val) const;
    bool                    GetAltSuppressLeadingZeros() const;
    void                    SetAltSuppressLeadingZeros(bool val) const;
    bool                    GetAltSuppressTrailingZeros() const;
    void                    SetAltSuppressTrailingZeros(bool val) const;
    bool                    GetAltSuppressZeroFeet() const;
    void                    SetAltSuppressZeroFeet(bool val) const;
    bool                    GetAltSuppressZeroInches() const;
    void                    SetAltSuppressZeroInches(bool val) const;
    bool                    GetAltToleranceSuppressLeadingZeros() const;
    void                    SetAltToleranceSuppressLeadingZeros(bool val) const;
    bool                    GetAltToleranceSuppressTrailingZeros() const;
    void                    SetAltToleranceSuppressTrailingZeros(bool val) const;
    bool                    GetAltToleranceSuppressZeroFeet() const;
    void                    SetAltToleranceSuppressZeroFeet(bool val) const;
    bool                    GetAltToleranceSuppressZeroInches() const;
    void                    SetAltToleranceSuppressZeroInches(bool val) const;
    bool                    GetSuppressZeroFeet() const;
    void                    SetSuppressZeroFeet(bool val) const;
    bool                    GetSuppressZeroInches() const;
    void                    SetSuppressZeroInches(bool val) const;
    bool                    GetToleranceSuppressZeroFeet() const;
    void                    SetToleranceSuppressZeroFeet(bool val) const;
    bool                    GetToleranceSuppressZeroInches() const;
    void                    SetToleranceSuppressZeroInches(bool val) const;
    double                  GetArrowheadSize() const;
    void                    SetArrowheadSize(double val) const;
    double                  GetMeasurement() const;
    bool                    GetExtLineFixedLenSuppress() const;
    void                    SetExtLineFixedLenSuppress(bool val) const;
    double                  GetExtLineFixedLen() const;
    void                    SetExtLineFixedLen(double val) const;
    CString                 GetSubUnitsSuffix() const;
    void                    SetSubUnitsSuffix(const CString& val) const;
    double                  GetSubUnitsFactor() const;
    void                    SetSubUnitsFactor(double val) const;
    CString                 GetAltSubUnitsSuffix() const;
    void                    SetAltSubUnitsSuffix(const CString& val) const;
    double                  GetAltSubUnitsFactor() const;
    void                    SetAltSubUnitsFactor(double val) const;

    IAcadDimOrdinate* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDimOrdinatePtr = std::unique_ptr<PyIAcadDimOrdinateImpl>;

//------------------------------------------------------------------------------------
//PyIAcadDimRadialImpl
class PyIAcadDimRadialImpl : public PyIAcadDimensionImpl
{
public:
    explicit PyIAcadDimRadialImpl(IAcadDimRadial* ptr);
    virtual ~PyIAcadDimRadialImpl() override = default;

    void                    SetLeaderLength(double val) const;
    bool                    GetAltUnits() const;
    void                    SetAltUnits(bool val) const;
    PyAcDimPrecision        GetAltUnitsPrecision() const;
    void                    SetAltUnitsPrecision(PyAcDimPrecision val) const;
    double                  GetAltUnitsScale() const;
    void                    SetAltUnitsScale(double val) const;
    double                  GetAltRoundDistance() const;
    void                    SetAltRoundDistance(double val) const;
    PyAcDimPrecision        GetAltTolerancePrecision() const;
    void                    SetAltTolerancePrecision(PyAcDimPrecision val) const;
    PyAcDimUnits            GetAltUnitsFormat() const;
    void                    SetAltUnitsFormat(PyAcDimUnits val) const;
    CString                 GetAltTextPrefix() const;
    void                    SetAltTextPrefix(const CString& val) const;
    CString                 GetAltTextSuffix() const;
    void                    SetAltTextSuffix(const CString& val) const;
    PyAcDimCenterType       GetCenterType() const;
    void                    SetCenterType(PyAcDimCenterType val) const;
    double                  GetCenterMarkSize() const;
    void                    SetCenterMarkSize(double val) const;
    PyAcColor               GetDimensionLineColor() const;
    void                    SetDimensionLineColor(PyAcColor val) const;
    PyAcDimPrecision        GetPrimaryUnitsPrecision() const;
    void                    SetPrimaryUnitsPrecision(PyAcDimPrecision val) const;
    PyAcDimFractionType     GetFractionFormat() const;
    void                    SetFractionFormat(PyAcDimFractionType val) const;
    PyAcDimFit              GetFit() const;
    void                    SetFit(PyAcDimFit val) const;
    double                  GetLinearScaleFactor() const;
    void                    SetLinearScaleFactor(double val) const;
    PyAcDimLUnits           GetUnitsFormat() const;
    void                    SetUnitsFormat(PyAcDimLUnits val) const;
    double                  GetRoundDistance() const;
    void                    SetRoundDistance(double val) const;
    bool                    GetDimLineSuppress() const;
    void                    SetDimLineSuppress(bool val) const;
    bool                    GetTextInsideAlign() const;
    void                    SetTextInsideAlign(bool val) const;
    bool                    GetTextInside() const;
    void                    SetTextInside(bool val) const;
    bool                    GetForceLineInside() const;
    void                    SetForceLineInside(bool val) const;
    bool                    GetTextOutsideAlign() const;
    void                    SetTextOutsideAlign(bool val) const;
    bool                    GetAltSuppressLeadingZeros() const;
    void                    SetAltSuppressLeadingZeros(bool val) const;
    bool                    GetAltSuppressTrailingZeros() const;
    void                    SetAltSuppressTrailingZeros(bool val) const;
    bool                    GetAltSuppressZeroFeet() const;
    void                    SetAltSuppressZeroFeet(bool val) const;
    bool                    GetAltSuppressZeroInches() const;
    void                    SetAltSuppressZeroInches(bool val) const;
    bool                    GetAltToleranceSuppressLeadingZeros() const;
    void                    SetAltToleranceSuppressLeadingZeros(bool val) const;
    bool                    GetAltToleranceSuppressTrailingZeros() const;
    void                    SetAltToleranceSuppressTrailingZeros(bool val) const;
    bool                    GetAltToleranceSuppressZeroFeet() const;
    void                    SetAltToleranceSuppressZeroFeet(bool val) const;
    bool                    GetAltToleranceSuppressZeroInches() const;
    void                    SetAltToleranceSuppressZeroInches(bool val) const;
    bool                    GetSuppressZeroFeet() const;
    void                    SetSuppressZeroFeet(bool val) const;
    bool                    GetSuppressZeroInches() const;
    void                    SetSuppressZeroInches(bool val) const;
    bool                    GetToleranceSuppressZeroFeet() const;
    void                    SetToleranceSuppressZeroFeet(bool val) const;
    bool                    GetToleranceSuppressZeroInches() const;
    void                    SetToleranceSuppressZeroInches(bool val) const;
    PyAcLineWeight          GetDimensionLineWeight() const;
    void                    SetDimensionLineWeight(PyAcLineWeight val) const;
    double                  GetArrowheadSize() const;
    void                    SetArrowheadSize(double val) const;
    PyAcDimArrowheadType    GetArrowheadType() const;
    void                    SetArrowheadType(PyAcDimArrowheadType val) const;
    double                  GetMeasurement() const;
    CString                 GetArrowheadBlock() const;
    void                    SetArrowheadBlock(const CString& val) const;
    CString                 GetDimensionLinetype() const;
    void                    SetDimensionLinetype(const CString& val) const;
    bool                    GetDimConstrForm() const;
    void                    SetDimConstrForm(bool val) const;
    bool                    GetDimConstrReference() const;
    void                    SetDimConstrReference(bool val) const;
    CString                 GetDimConstrName() const;
    void                    SetDimConstrName(const CString& val) const;
    CString                 GetDimConstrExpression() const;
    void                    SetDimConstrExpression(const CString& val) const;
    CString                 GetDimConstrValue() const;
    void                    SetDimConstrValue(const CString& val) const;
    CString                 GetDimConstrDesc() const;
    void                    SetDimConstrDesc(const CString& val) const;

    IAcadDimRadial* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDimRadialPtr = std::unique_ptr<PyIAcadDimRadialImpl>;

//------------------------------------------------------------------------------------
//PyIAcadDim3PointAngularImpl
class PyIAcadDim3PointAngularImpl : public PyIAcadDimensionImpl
{
public:
    explicit PyIAcadDim3PointAngularImpl(IAcadDim3PointAngular* ptr);
    virtual ~PyIAcadDim3PointAngularImpl() override = default;

    AcGePoint3d             GetExtLine1EndPoint() const;
    void                    SetExtLine1EndPoint(const AcGePoint3d& val) const;
    AcGePoint3d             GetExtLine2EndPoint() const;
    void                    SetExtLine2EndPoint(const AcGePoint3d& val) const;
    AcGePoint3d             GetAngleVertex() const;
    void                    SetAngleVertex(const AcGePoint3d& val) const;
    PyAcDimPrecision        GetTextPrecision() const;
    void                    SetTextPrecision(PyAcDimPrecision val) const;
    PyAcAngleUnits          GetAngleFormat() const;
    void                    SetAngleFormat(PyAcAngleUnits val) const;
    PyAcColor               GetDimensionLineColor() const;
    void                    SetDimensionLineColor(PyAcColor val) const;
    PyAcColor               GetExtensionLineColor() const;
    void                    SetExtensionLineColor(PyAcColor val) const;
    double                  GetExtensionLineExtend() const;
    void                    SetExtensionLineExtend(double val) const;
    PyAcDimFit              GetFit() const;
    void                    SetFit(PyAcDimFit val) const;
    PyAcDimHorizontalJustification     GetHorizontalTextPosition() const;
    void                               SetHorizontalTextPosition(PyAcDimHorizontalJustification val) const;
    PyAcLineWeight          GetExtensionLineWeight() const;
    void                    SetExtensionLineWeight(PyAcLineWeight val) const;
    bool                    GetDimLine1Suppress() const;
    void                    SetDimLine1Suppress(bool val) const;
    bool                    GetDimLine2Suppress() const;
    void                    SetDimLine2Suppress(bool val) const;
    bool                    GetExtLine1Suppress() const;
    void                    SetExtLine1Suppress(bool val) const;
    bool                    GetExtLine2Suppress() const;
    void                    SetExtLine2Suppress(bool val) const;
    bool                    GetDimLineInside() const;
    void                    SetDimLineInside(bool val) const;
    bool                    GetTextInsideAlign() const;
    void                    SetTextInsideAlign(bool val) const;
    bool                    GetTextInside() const;
    void                    SetTextInside(bool val) const;
    bool                    GetForceLineInside() const;
    void                    SetForceLineInside(bool val) const;
    bool                    GetTextOutsideAlign() const;
    void                    SetTextOutsideAlign(bool val) const;
    double                  GetExtensionLineOffset() const;
    void                    SetExtensionLineOffset(double val) const;
    PyAcLineWeight          GetDimensionLineWeight() const;
    void                    SetDimensionLineWeight(PyAcLineWeight val) const;
    double                  GetArrowheadSize() const;
    void                    SetArrowheadSize(double val) const;
    PyAcDimArrowheadType    GetArrowhead1Type() const;
    void                    SetArrowhead1Type(PyAcDimArrowheadType val) const;
    PyAcDimArrowheadType    GetArrowhead2Type() const;
    void                    SetArrowhead2Type(PyAcDimArrowheadType val) const;
    double                  GetMeasurement() const;
    CString                 GetArrowhead1Block() const;
    void                    SetArrowhead1Block(const CString& val) const;
    CString                 GetArrowhead2Block() const;
    void                    SetArrowhead2Block(const CString& val) const;
    CString                 GetDimensionLinetype() const;
    void                    SetDimensionLinetype(const CString& val) const;
    CString                 GetExtLine1Linetype() const;
    void                    SetExtLine1Linetype(const CString& val) const;
    CString                 GetExtLine2Linetype() const;
    void                    SetExtLine2Linetype(const CString& val) const;
    bool                    GetExtLineFixedLenSuppress() const;
    void                    SetExtLineFixedLenSuppress(bool val) const;
    double                  GetExtLineFixedLen() const;
    void                    SetExtLineFixedLen(double val) const;
    bool                    GetDimConstrForm() const;
    void                    SetDimConstrForm(bool val) const;
    bool                    GetDimConstrReference() const;
    void                    SetDimConstrReference(bool val) const;
    CString                 GetDimConstrName() const;
    void                    SetDimConstrName(const CString& val) const;
    CString                 GetDimConstrExpression() const;
    void                    SetDimConstrExpression(const CString& val) const;
    CString                 GetDimConstrValue() const;
    void                    SetDimConstrValue(const CString& val) const;
    CString                 GetDimConstrDesc() const;
    void                    SetDimConstrDesc(const CString& val) const;

    IAcadDim3PointAngular* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDim3PointAngularPtr = std::unique_ptr<PyIAcadDim3PointAngularImpl>;

//------------------------------------------------------------------------------------
//PyIAcadDimArcLengthImpl
class PyIAcadDimArcLengthImpl : public PyIAcadDimensionImpl
{
public:
    explicit PyIAcadDimArcLengthImpl(IAcadDimArcLength* ptr);
    virtual ~PyIAcadDimArcLengthImpl() override = default;
    IAcadDimArcLength* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDimArcLengthPtr = std::unique_ptr<PyIAcadDimArcLengthImpl>;

//------------------------------------------------------------------------------------
//PyIAcadDimRadialLargeImpl
class PyIAcadDimRadialLargeImpl : public PyIAcadDimensionImpl
{
public:
    explicit PyIAcadDimRadialLargeImpl(IAcadDimRadialLarge* ptr);
    virtual ~PyIAcadDimRadialLargeImpl() override = default;
    IAcadDimRadialLarge* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadDimRadialLargePtr = std::unique_ptr<PyIAcadDimRadialLargeImpl>;