#pragma once
#include "PyAcadEntityImpl.h"

//------------------------------------------------------------------------------------
//PyIAcadTableImpl
class PyIAcadTableImpl : public PyIAcadEntityImpl
{
public:
    explicit PyIAcadTableImpl(IAcadTable* ptr);
    virtual ~PyIAcadTableImpl() override = default;

    CString             GetStyleName() const;
    void                SetStyleName(const CString val) const;
    int                 GetRows() const;
    void                SetRows(int val) const;
    int                 GetColumns() const;
    void                SetColumns(int val) const;
    PyAcTableDirection  GetFlowDirection() const;
    void                SetFlowDirection(PyAcTableDirection val) const;
    double              GetWidth() const;
    void                SetWidth(double val) const;
    double              GetHeight() const;
    void                SetHeight(double val) const;
    double              GetVertCellMargin() const;
    void                SetVertCellMargin(double val) const;
    double              GetHorzCellMargin() const;
    void                SetHorzCellMargin(double val) const;
    AcGePoint3d         GetInsertionPoint() const;
    void                SetInsertionPoint(const AcGePoint3d val) const;
    double              GetColumnWidth(int col) const;
    void                SetColumnWidth(double val) const;
    void                SetColumnWidth(int col, double val) const;
    double              GetRowHeight(int row) const;
    void                SetRowHeight(double val) const;
    void                SetRowHeight(int row, double val) const;
    double              GetMinimumColumnWidth(int col) const;
    double              GetMinimumRowHeight(int row) const;
    double              GetMinimumTableWidth() const;
    double              GetMinimumTableHeight() const;
    AcGeVector3d        GetDirection() const;
    void                SetDirection(const AcGeVector3d& val) const;
    bool                GetTitleSuppressed() const;
    void                SetTitleSuppressed(bool val) const;
    bool                GetHeaderSuppressed() const;
    void                SetHeaderSuppressed(bool val) const;
    Int32s              GetTableStyleOverrides() const;
    void                ClearTableStyleOverrides(int flag) const;
    PyAcCellType        GetCellType(int row, int col) const;
    void                SetCellType(int row, int col, PyAcCellType val) const;
    Point3dCoordinates  GetCellExtents(int row, int col, bool bOuterCell) const;
    AcGePoint3d         GetAttachmentPoint(int row, int col) const;
    PyAcCellAlignment   GetCellAlignment(int row, int col) const;
    void                SetCellAlignment(int row, int col, PyAcCellAlignment val) const;
    bool                GetCellBackgroundColorNone(int row, int col) const;
    void                SetCellBackgroundColorNone(int row, int col, bool val) const;
    PyIAcadAcCmColorPtr GetCellBackgroundColor(int row, int col) const;
    void                SetCellBackgroundColor(int row, int col, const PyIAcadAcCmColorImpl& val) const;
    PyIAcadAcCmColorPtr GetCellContentColor(int row, int col) const;
    void                SetCellContentColor(int row, int col, const PyIAcadAcCmColorImpl& val) const;
    Int32s              GetCellStyleOverrides(int row, int col) const;
    void                DeleteCellContent(int row, int col) const;
    PyAcRowType         GetRowType(int row) const;
    CString             GetText(int row, int col) const;
    void                SetText(int row, int col, const CString& val) const;
    CString             GetCellTextStyle(int row, int col) const;
    void                SetCellTextStyle(int row, int col, const CString& val) const;
    double              GetCellTextHeight(int row, int col) const;
    void                SetCellTextHeight(int row, int col, double val) const;
    PyAcRotationAngle   GetTextRotation(int row, int col) const;
    void                SetTextRotation(int row, int col, PyAcRotationAngle val) const;
    bool                GetAutoScale(int row, int col) const;
    void                SetAutoScale(int row, int col, bool val) const;
    AcDbObjectId        GetBlockTableRecordId(int row, int col) const;
    void                SetBlockTableRecordId(int row, int col, const AcDbObjectId& val, bool autoScale) const;
    double              GetBlockScale(int row, int col) const;
    void                SetBlockScale(int row, int col, double val) const;
    double              GetBlockRotation(int row, int col) const;
    void                SetBlockRotation(int row, int col, double val) const;
    CString             GetBlockAttributeValue(int row, int col, const AcDbObjectId& val) const;
    void                SetBlockAttributeValue(int row, int col, const AcDbObjectId& id, const CString& val) const;
    PyAcLineWeight      GetCellGridLineWeight(int row, int col, PyAcCellEdgeMask mask) const;
    void                SetCellGridLineWeight(int row, int col, PyAcCellEdgeMask mask, PyAcLineWeight lw) const;
    PyIAcadAcCmColorPtr GetCellGridColor(int row, int col, PyAcCellEdgeMask mask) const;
    void                SetCellGridColor(int row, int col, PyAcCellEdgeMask mask, const PyIAcadAcCmColorImpl& val) const;
    bool                GetCellGridVisibility(int row, int col, PyAcCellEdgeMask mask) const;
    void                SetCellGridVisibility(int row, int col, PyAcCellEdgeMask mask, bool val) const;
    void                InsertColumns(int col, double width, int cols) const;
    void                DeleteColumns(int col, int cols) const;
    void                InsertRows(int row, double width, int rows) const;
    void                DeleteRows(int row, int rows) const;
    void                MergeCells(int minRow, int maxRow, int minCol, int maxCol) const;
    void                UnmergeCells(int minRow, int maxRow, int minCol, int maxCol) const;
    bool                IsMergedCell(int row, int col, int& minRow, int& maxRow, int& minCol, int& maxCol) const;
    AcDbObjectId        GetFieldId(int row, int col) const;
    void                SetFieldId(int row, int col, const AcDbObjectId& id) const;
    void                GenerateLayout() const;
    void                RecomputeTableBlock(bool bForceUpdate) const;
    boost::python::tuple HitTest(const AcGePoint3d& wpt, const AcGeVector3d& wviewVec) const;
    boost::python::tuple Select(const AcGePoint3d& wpt, const AcGeVector3d& wvwVec, const AcGeVector3d& wvwxVec, double wxaper, double wyaper, bool allowOutside) const;
    boost::python::tuple SelectSubRegion(const AcGePoint3d& wpt1, const AcGePoint3d& wpt2, const AcGeVector3d& wvwVec, const AcGeVector3d& wvwxVec, PyAcSelectType seltype, bool bIncludeCurrent) const;
    boost::python::tuple GetSubSelection() const;
    void                SetSubSelection(int minRow, int maxRow, int minCol, int maxCol) const;
    void                ReselectSubRegion() const;
    void                ClearSubSelection() const;
    bool                GetHasSubSelection() const;
    bool                GetRegenerateTableSuppressed() const;
    void                SetRegenerateTableSuppressed(bool val) const;
    CString             FormatValue(int row, int col, PyAcFormatOption fmt) const;
    boost::python::tuple GetCellDataType(int row, int col) const;
    void                SetCellDataType(int row, int col, PyAcValueDataType dataType, PyAcValueUnitType unitType) const;
    CString             GetCellFormat(int row, int col) const;
    void                SetCellFormat(int row, int col, const CString& val) const;
    AcValue             GetCellValue(int row, int col) const;
    void                SetCellValue(int row, int col, const AcValue& val) const;
    void                SetCellValueFromText(int row, int col, const CString& val, PyAcParseOption nOption) const;
    void                ResetCellValue(int row, int col) const;
    bool                IsEmpty(int row, int col) const;
    int                 CreateContent(int row, int col, int nIndex) const;
    void                MoveContent(int row, int col, int nFromIndex, int nToIndex) const;
    void                DeleteContent(int row, int col) const;
    AcValue             GetValue(int row, int col, int nContent) const;
    void                SetValue(int row, int col, int nContent, const AcValue& val) const;
    void                SetValueFromText(int row, int col, int nContent, const CString& val, PyAcParseOption nOption) const;
    CString             GetDataFormat(int row, int col, int nContent) const;
    void                SetDataFormat(int row, int col, int nContent, const CString& val) const;
    CString             GetTextString(int row, int col, int nContent) const;
    void                SetTextString(int row, int col, int nContent, const CString& val) const;
    AcDbObjectId        GetFieldId2(int row, int col, int nContent) const;
    void                SetFieldId2(int row, int col, int nContent, const AcDbObjectId& val, PyAcCellOption nflag) const;
    AcDbObjectId        GetBlockTableRecordId2(int row, int col, int nContent) const;
    void                SetBlockTableRecordId2(int row, int col, int nContent, const AcDbObjectId& val, bool autoScale) const;
    CString             GetBlockAttributeValue2(int row, int col, int nContent, const AcDbObjectId& val) const;
    void                SetBlockAttributeValue2(int row, int col, int nContent, const AcDbObjectId& id, const CString& val) const;
    AcValue             GetCustomData(int row, int col, const CString& key) const;
    void                SetCustomData(int row, int col, const CString& key, const AcValue& val) const;
    CString             GetCellStyle(int row, int col) const;
    void                SetCellStyle(int row, int col, const CString& val) const;
    PyIAcadAcCmColorPtr GetContentColor2(int row, int col, int nContent) const;
    void                SetContentColor2(int row, int col, int nContent, const PyIAcadAcCmColorImpl& val) const;
    boost::python::tuple GetDataType2(int row, int col, int nContent) const;
    void                SetDataType2(int row, int col, int nContent, PyAcValueDataType dataType, PyAcValueUnitType unitType) const;
    CString             GetTextStyle2(int row, int col, int nContent) const;
    void                SetTextStyle2(int row, int col, int nContent, const CString& val) const;
    double              GetTextHeight2(int row, int col, int nContent) const;
    void                SetTextHeight2(int row, int col, int nContent, double val) const;
    double              GetRotation(int row, int col, int nContent) const;
    void                SetRotation(int row, int col, int nContent, double val) const;
    bool                GetAutoScale2(int row, int col, int nContent) const;
    void                SetAutoScale2(int row, int col, int nContent, bool val) const;
    double              SetScale(int row, int col, int nContent) const;
    void                SetScale(int row, int col, int nContent, double val) const;
    void                RemoveAllOverrides(int row, int col) const;
    PyAcLineWeight      GetGridLineWeight2(int row, int col, PyAcGridLineType lt) const;
    void                SetGridLineWeight2(int row, int col, PyAcGridLineType lt, PyAcLineWeight lw) const;
    AcDbObjectId        GetGridLinetype(int row, int col, PyAcGridLineType lt) const;
    void                SetGridLinetype(int row, int col, PyAcGridLineType lt, const AcDbObjectId& val) const;
    PyIAcadAcCmColorPtr GetGridColor2(int row, int col, PyAcGridLineType lt) const;
    void                SetGridColor2(int row, int col, PyAcGridLineType lt, const PyIAcadAcCmColorImpl& val) const;
    bool                GetGridVisibility2(int row, int col, PyAcGridLineType lt) const;
    void                SetGridVisibility2(int row, int col, PyAcGridLineType lt, bool val) const;
    double              GetGridDoubleLineSpacing(int row, int col, PyAcGridLineType lt) const;
    void                GetGridDoubleLineSpacing(int row, int col, PyAcGridLineType lt, double val) const;
    void                SetEnableBreak(bool val) const;
    double              GetBreakHeight(int nIndex) const;
    void                SetBreakHeight(int nIndex, double val) const;
    PyAcCellContentType GetContentType(int row, int col) const;
    double              GetMargin(int row, int col, PyAcCellMargin margin) const;
    void                SetMargin(int row, int col, PyAcCellMargin margin, double val) const;
    PyAcCellContentLayout GetContentLayout(int row, int col) const;
    void                  SetContentLayout(int row, int col, PyAcCellContentLayout val) const;
    PyAcCellProperty    GetOverride(int row, int col, int nContent) const;
    void                SetOverride(int row, int col, int nContent, PyAcCellProperty val) const;
    PyAcGridLineStyle   GetGridLineStyle(int row, int col, PyAcGridLineType lt) const;
    void                SetGridLineStyle(int row, int col, PyAcGridLineType lt, PyAcGridLineStyle val) const;
    void                InsertRowsAndInherit(int nIndex, int nInheritFrom, int nNumRows) const;
    void                InsertColumnsAndInherit(int nIndex, int nInheritFrom, int nNumCols) const;
    bool                GetHasFormula(int row, int col, int nContent) const;
    CString             GetFormula(int row, int col, int nContent) const;
    void                SetFormula(int row, int col, int nContent, const CString& val) const;
    bool                IsContentEditable(int row, int col) const;
    bool                IsFormatEditable(int row, int col) const;
    PyAcCellState       GetCellState(int row, int col) const;
    void                SetCellState(int row, int col, PyAcCellState val) const;
    void                EnableMergeAll(int row, int col, bool val) const;
    bool                IsMergeAllEnabled(int row, int col) const;
    bool                GetBreaksEnabled() const;
    void                SetBreaksEnabled(bool val) const;
    bool                GetRepeatTopLabels() const;
    void                SetRepeatTopLabels(bool val) const;
    bool                GetRepeatBottomLabels() const;
    void                SetRepeatBottomLabels(bool val) const;
    PyAcTableFlowDirection GetTableBreakFlowDirection() const;
    void                   SetTableBreakFlowDirection(PyAcTableFlowDirection val) const;
    bool                GetAllowManualPositions() const;
    void                SetAllowManualPositions(bool val) const;
    bool                GetAllowManualHeights() const;
    void                SetAllowManualHeights(bool val) const;
    double              GetTableBreakHeight() const;
    void                SetTableBreakHeight(double val) const;
    double              GetBreakSpacing() const;
    void                SetBreakSpacing(double val) const;
    CString             GetColumnName(int col) const;
    void                SetColumnName(int col,const CString& val) const;
    void                SetToolTip(int row, int col, const CString& val) const;


    IAcadTable* impObj(const std::source_location& src = std::source_location::current()) const;
};
using PyIAcadTablePtr = std::unique_ptr<PyIAcadTableImpl>;
