#pragma once
#include "PyDbEntity.h"

#pragma pack (push, 8)

class PyDbObjectId;
class PyDbXrefObjectId;
class PyDbAnnotationScale;

void makePyDbViewportWrapper();

class PyDbViewport : public PyDbEntity
{
public:
    PyDbViewport();
    PyDbViewport(AcDbViewport* ptr, bool autoDelete);
    PyDbViewport(const PyDbObjectId& id);
    PyDbViewport(const PyDbObjectId& id, AcDb::OpenMode mode);
    PyDbViewport(const PyDbObjectId& id, AcDb::OpenMode mode,bool erased);
    virtual ~PyDbViewport() override = default;
    void                setModelView(const PyDbXrefObjectId& xrefObjId) const;
    PyDbXrefObjectId    getModelView() const;
    void                removeModelView(void) const;
    void                setSheetView(PyDbObjectId objId) const;
    PyDbObjectId        getSheetView()const;
    void                removeSheetView(void) const;
    void                setLabelBlock(PyDbObjectId& objId) const;
    PyDbObjectId        getLabelBlock() const;
    void                removeLabelBlock(void) const;
    void                syncModelView(void) const;
    double              height() const;
    void                setHeight(double val) const;
    double              width() const;
    void                setWidth(double val) const;
    AcGePoint3d         centerPoint() const;
    void                setCenterPoint(const AcGePoint3d& val) const;
    Adesk::Int16        number() const;
    bool                isOn() const;
    void                setOn() const;
    void                setOff() const;
    void                setIsOn(bool bOn) const;
    AcGePoint3d         viewTarget() const;
    void                setViewTarget(const AcGePoint3d& val) const;
    AcGeVector3d        viewDirection() const;
    void                setViewDirection1(const AcGeVector3d& val) const;
    double              viewHeight() const;
    void                setViewHeight(double ht) const;
    AcGePoint2d         viewCenter() const;
    void                setViewCenter(const AcGePoint2d& pt) const;
    double              twistAngle() const;
    void                setTwistAngle(double val) const;
    double              lensLength() const;
    void                setLensLength(double val) const;
    bool                isFrontClipOn() const;
    void                setFrontClipOn1() const;
    void                setFrontClipOff() const;
    void                setFrontClipOn2(bool bOn) const;
    bool                isBackClipOn() const;
    void                setBackClipOn1() const;
    void                setBackClipOff() const;
    void                setBackClipOn2(bool bOn) const;
    bool                isFrontClipAtEyeOn() const;
    void                setFrontClipAtEyeOn1() const;
    void                setFrontClipAtEyeOff() const;
    void                setFrontClipAtEyeOn2(bool bOn) const;
    double              frontClipDistance() const;
    void                setFrontClipDistance(double newVal) const;
    double              backClipDistance() const;
    void                setBackClipDistance(double newVal) const;
    bool                isPerspectiveOn() const;
    void                setPerspectiveOn1() const;
    void                setPerspectiveOff() const;
    void                setPerspectiveOn2(bool bOn) const;
    bool                isUcsFollowModeOn() const;
    void                setUcsFollowModeOn1() const;
    void                setUcsFollowModeOff() const;
    void                setUcsFollowModeOn2(bool bOn) const;
    bool                isUcsIconVisible() const;
    void                setUcsIconVisible1() const;
    void                setUcsIconInvisible() const;
    void                setUcsIconVisible2(bool bOn) const;
    bool                isUcsIconAtOrigin() const;
    void                setUcsIconAtOrigin1() const;
    void                setUcsIconAtCorner() const;
    void                setUcsIconAtOrigin2(bool) const;
    bool                isFastZoomOn() const;
    void                setFastZoomOn1() const;
    void                setFastZoomOff() const;
    void                setFastZoomOn2(bool bOn) const;
    Adesk::UInt16       circleSides() const;
    void                setCircleSides(Adesk::UInt16 val) const;
    bool                isSnapOn() const;
    void                setSnapOn1() const;
    void                setSnapOff() const;
    void                setSnapOn2(bool bOn) const;
    bool                isSnapIsometric() const;
    void                setSnapIsometric1() const;
    void                setSnapStandard() const;
    void                setSnapIsometric2(bool bOn) const;
    double              snapAngle() const;
    void                setSnapAngle(double val) const;
    AcGePoint2d         snapBasePoint() const;
    void                setSnapBasePoint(const AcGePoint2d& val) const;
    AcGeVector2d        snapIncrement() const;
    void                setSnapIncrement(const AcGeVector2d& val) const;
    Adesk::UInt16       snapIsoPair() const;
    void                setSnapIsoPair(Adesk::UInt16 val) const;
    bool                isGridOn() const;
    void                setGridOn1() const;
    void                setGridOff() const;
    void                setGridOn2(bool val) const;
    bool                isGridBoundToLimits() const;
    void                setGridBoundToLimits(bool bNewVal) const;
    bool                isGridAdaptive() const;
    void                setGridAdaptive(bool bNewVal) const;
    bool                isGridSubdivisionRestricted() const;
    void                setGridSubdivisionRestricted(bool bNewVal) const;
    bool                isGridFollow() const;
    void                 setGridFollow(bool bNewVal) const;
    Adesk::UInt16       gridMajor() const;
    void                setGridMajor(Adesk::UInt16 val) const;
    AcGeVector2d        gridIncrement() const;
    void                setGridIncrement(const AcGeVector2d& val) const;
    bool                hiddenLinesRemoved() const;
    void                showHiddenLines() const;
    void                removeHiddenLines1() const;
    void                removeHiddenLines2(bool val) const;
    void                freezeLayersInViewport(const boost::python::list& ids) const;
    void                thawLayersInViewport(const boost::python::list& pyids) const;
    void                thawAllLayersInViewport() const;
    bool                isLayerFrozenInViewport(const PyDbObjectId& layerId) const;
    boost::python::list getFrozenLayerList() const;
    void                updateDisplay() const;
    PyDbObjectId        background() const;
    void                setBackground(PyDbObjectId& backgroundId) const;
    PyDbObjectId        previousBackground1() const;
    PyDbObjectId        previousBackground2(AcGiDrawable::DrawableType type) const;
    void                setPreviousBackground1(PyDbObjectId& backgroundId) const;
    void                setPreviousBackground2(PyDbObjectId& backgroundId, AcGiDrawable::DrawableType type) const;
    void                setPreviousBackground3(PyDbObjectId& backgroundId, AcGiDrawable::DrawableType type, bool force) const;
    bool                previousBackgroundForcedSwitch(void) const;
    PyDbObjectId        visualStyle() const;
    void                setVisualStyle(const PyDbObjectId& oidVisualStyle) const;
    bool                isDefaultLightingOn() const;
    void                setDefaultLightingOn(bool on) const;
    AcGiViewportTraits::DefaultLightingType defaultLightingType() const;
    void                setDefaultLightingType(AcGiViewportTraits::DefaultLightingType typ) const;
    double              brightness() const;
    void                setBrightness(double val) const;
    double              contrast() const;
    void                setContrast(double val) const;
    AcCmColor           ambientLightColor() const;
    void                setAmbientLightColor(const AcCmColor& clr) const;
    PyDbObjectId        sunId() const;
    void                setSun1(PyDbObjectId& retId, PyDbObject& pSun) const;
    void                setSun2(PyDbObjectId& retId, PyDbObject& pSun, bool eraseOldSun) const;
    bool                isLocked() const;
    void                setLocked1() const;
    void                setUnlocked() const;
    void                setLocked2(bool val) const;
    PyDbAnnotationScale annotationScale() const;
    void                setAnnotationScale(const PyDbAnnotationScale& pScaleObj) const;
    bool                isTransparent() const;
    void                setTransparent1() const;
    void                setOpaque() const;
    void                setTransparent2(bool val) const;
    double              customScale() const;
    void                setCustomScale(double val) const;
    AcDbViewport::StandardScaleType standardScale() const;
    void                setStandardScale(const AcDbViewport::StandardScaleType val) const;
    std::string         plotStyleSheet() const;
    std::string         effectivePlotStyleSheet() const;
    void                setPlotStyleSheet(const std::string& val) const;
    bool                isNonRectClipOn() const;
    void                setNonRectClipOn1() const;
    void                setNonRectClipOff() const;
    void                setNonRectClipOn2(bool bOn) const;
    PyDbObjectId        nonRectClipEntityId() const;
    void                setNonRectClipEntityId(const PyDbObjectId& val) const;
    void                erased(const PyDbObject& obj, Adesk::Boolean val) const;
    void                modified(const PyDbObject& obj) const;
    void                copied(const PyDbObject& pDbObj, const PyDbObject& pNewObj) const;
    void                subObjModified(const PyDbObject& pDbObj, const PyDbObject& pSubObj) const;
    boost::python::tuple getUcs() const;
    boost::python::tuple isUcsOrthographic() const;
    PyDbObjectId        ucsName() const;
    double              elevation() const;
    void                setUcs1(const AcGePoint3d& origin,const AcGeVector3d& xAxis, const AcGeVector3d& yAxis) const;
    void                setUcs2(AcDb::OrthographicView view) const;
    void                setUcs3(const PyDbObjectId& ucsId) const;
    void                setUcsToWorld() const;
    void                setElevation(double elev) const;
    boost::python::tuple isViewOrthographic() const;
    void                setViewDirection2(AcDb::OrthographicView view) const;
    bool                isUcsSavedWithViewport() const;
    void                setUcsPerViewport(bool ucsvp) const;
    AcDbViewport::ShadePlotType shadePlot() const;
    void                setShadePlot1(const AcDbViewport::ShadePlotType) const;
    PyDbObjectId        shadePlotId() const;
    void                setShadePlot2(const AcDbViewport::ShadePlotType type,const PyDbObjectId shadePlotId) const;
    bool                plotWireframe() const;
    bool                plotAsRaster()  const;
    //void toneOperatorParameters(AcGiToneOperatorParameters& params) const;
    //void setToneOperatorParameters(const AcGiToneOperatorParameters& params);
    static std::string      className();
    static PyRxClass        desc();
    static PyDbViewport     cloneFrom(const PyRxObject& src);
    static PyDbViewport     cast(const PyRxObject& src);
public:
    AcDbViewport* impObj(const std::source_location& src = std::source_location::current()) const;
};

#pragma pack (pop)
