#pragma once
#include "PyRxObject.h"

#pragma pack (push, 8)
class PyDbObject;
class PyDbObjectId;
class PyDbEntity;
class PyDbTransactionManager;
class PyDbHandle;
class PyDbAnnotationScale;
class PyDbDimStyleTableRecord;
class PyDbIdMapping;
class PyDbDatabaseReactor;
class PyDbDate;
class PyDbObjectContextManager;
class PyDbDbLayerStateManager;
class PyAcadDatabase;
class PyObjectIdGraph;

typedef std::vector<PyDbObjectId> PyDbObjectIdArray;

void makePyDbDatabaseWrapper();

class PyDbDatabase : public PyRxObject
{
public:
    PyDbDatabase();
    PyDbDatabase(AcDbDatabase* pDb);
    PyDbDatabase(AcDbDatabase* pDb, bool autoDelete);
    PyDbDatabase(bool buildDefaultDrawing, bool noDocument);
    virtual ~PyDbDatabase() override = default;
    PyAcadDatabase      acadDatabase() const;
    PyDbObjectId        addToBlock1(const PyDbObjectId& id, PyDbEntity& ent) const;
    boost::python::list addToBlock2(const PyDbObjectId& id, const boost::python::list& ent) const;
    PyDbObjectId        addToModelspace1(PyDbEntity& ent) const;
    boost::python::list addToModelspace2(const boost::python::list& ent) const;
    PyDbObjectId        addToCurrentspace1(PyDbEntity& ent) const;
    boost::python::list addToCurrentspace2(const boost::python::list& ent) const;
    PyDbObjectId        addAcDbObject(PyDbObject& obj) const;
    void                addReactor(PyDbDatabaseReactor& pReactor) const;
    double              angbase() const;
    bool                angdir() const;
    bool                annoAllVisible() const;
    bool                annotativeDwg() const;
    int                 approxNumObjects() const;
    Adesk::Int16        attmode() const;
    Adesk::Int16        aunits() const;
    Adesk::Int16        auprec() const;
    bool                blipmode() const;
    PyDbObjectId        byBlockLinetype() const;
    PyDbObjectId        byBlockMaterial() const;
    PyDbObjectId        byLayerLinetype() const;
    PyDbObjectId        byLayerMaterial() const;
    bool                cameraDisplay() const;
    double              cameraHeight() const;
    Adesk::Int16        cDynDisplayMode() const;
    double              celtscale() const;
    PyDbObjectId        celtype() const;
    AcDb::LineWeight    celweight() const;
    double              chamfera() const;
    double              chamferb() const;
    double              chamferc() const;
    double              chamferd() const;
    std::string         classDxfName(const PyRxClass& pClass) const;
    PyDbObjectId        clayer() const;
    void                closeInput(bool bCloseFile) const;
    PyDbObjectId        cmaterial() const;
    Adesk::Int16        cmljust() const;
    double              cmlscale() const;
    PyDbObjectId        cmlstyleID() const;
    PyDbObjectId        colorDictionaryId() const;
    PyDbObjectId        continuousLinetype() const;
    Adesk::Int16        coords() const;
    Adesk::UInt32       countEmptyObjects(const Adesk::Int32 flags) const;
    Adesk::UInt32       countHardReferences(const boost::python::list& pyids) const;
    PyDbObjectId        detailViewStyle() const;
    PyDbObjectId        detailViewStyleDictionaryId() const;
    bool                dimaso() const;
    Adesk::UInt8        dimAssoc() const;
    int                 dimfit() const;
    bool                dimsho() const;
    PyDbObjectId        dimstyle() const;
    PyDbObjectId        dimStyleTableId() const;
    int                 dimunit() const;
    void                disablePartialOpen() const;
    void                disableUndoRecording(bool disable) const;
    bool                dispSilh() const;
    Adesk::Int16        dragmode() const;
    PyDbObjectId        dragVisStyle() const;
    Adesk::UInt8        drawOrderCtl() const;
    Adesk::UInt8        dwfframe() const;
    bool                dwgFileWasSavedByAutodeskSoftware() const;
    void                dxfIn(const std::string& dxfFilename) const;
    void                dxfOut1(const std::string& dxfFilename) const;
    void                dxfOut2(const std::string& dxfFilename, int precision, AcDb::AcDbDwgVersion dwgVer, bool saveThumbnailImage) const;
    double              elevation() const;
    Adesk::UInt32       eraseEmptyObjects(const Adesk::Int32 flags) const;
    AcGePoint3d         extmax() const;
    AcGePoint3d         extmin() const;
    double              facetres() const;
    double              filletrad() const;
    bool                fillmode() const;
    void                forceWblockDatabaseCopy() const;
    PyDbDbLayerStateManager getLayerStateManager() const;
    std::string         geoCoordinateSystemId() const;
    bool                geoMarkerVisibility() const;
    double              get3dDwfPrec() const;
    boost::python::list objectIds() const;
    boost::python::list objectIdsOfType(const PyRxClass& _class) const;
    boost::python::list objectIdsOfTypeList(const boost::python::list& _classes) const;//must be list
    PyDbObjectIdArray   objectIdArray1() const;
    PyDbObjectIdArray   objectIdArray2(const PyRxClass& _class) const;
    PyDbObjectIdArray   objectIdArray3(const boost::python::list& _classes) const;
    PyDbObjectId        getAcDbObjectId1(bool createIfNotFound, const PyDbHandle& objHandle) const;
    PyDbObjectId        getAcDbObjectId2(bool createIfNotFound, const PyDbHandle& objHandle, Adesk::UInt32 xRefId) const;
    PyDbObjectId        tryGetAcDbObjectId1(bool createIfNotFound, const PyDbHandle& objHandle) const;
    PyDbObjectId        tryGetAcDbObjectId2(bool createIfNotFound, const PyDbHandle& objHandle, Adesk::UInt32 xRefId) const;
    AcDb::PlotStyleNameType getCePlotStyleNameId(PyDbObjectId& id) const;
    bool                isAppRegistered(const std::string& pszAppName) const;
    std::string         dimapost() const;
    PyDbObjectId        dimblk() const;
    PyDbObjectId        dimblk1() const;
    PyDbObjectId        dimblk2() const;
    std::string         dimpost() const;
    PyDbObjectId        getDimstyleParentId(PyDbObjectId& childStyle) const;
    static AcDb::LineWeight getNearestLineWeight(int weight);
    PyDbObjectId        getSectionManagerId() const;
    boost::python::list getViewportArray1() const;
    boost::python::list getViewportArray2(bool bGetPaperspaceVports) const;
    boost::python::list getVisualStyleList() const; //TODO test
    PyDbObjectId        globalMaterial() const;
    PyDbObjectId        groupDictionaryId() const;
    void                insert1(PyDbObjectId& blockId, const std::string& pBlockName, PyDbDatabase& db, bool preserveSourceDatabase) const;
    void                insert2(PyDbObjectId& blockId, const std::string& pSourceBlockName, const std::string& pDestinationBlockName, PyDbDatabase& db, bool preserveSourceDatabase) const;
    void                insert3(const AcGeMatrix3d& xform, PyDbDatabase& db, bool preserveSourceDatabase) const;
    Adesk::UInt8        haloGap() const;
    PyDbHandle          handseed() const;
    bool                hasClass(const PyRxClass& pClass) const;
    Adesk::UInt8        hideText() const;
    bool                hpInherit() const;
    AcGePoint2d         hpOrigin() const;
    Adesk::UInt8        indexctl() const;
    AcDb::UnitsValue    insunits() const;
    PyDbObjectId        interfereVpVisStyle() const;
    Adesk::UInt16       intersectColor() const;
    Adesk::UInt8        intersectDisplay() const;
    bool                isBeingDestroyed() const;
    bool                isEMR() const;
    static bool         isObjectNonPersistent(const PyDbObjectId& id);
    Adesk::Int16        isolines() const;
    bool                isPartiallyOpened() const;
    bool                isPucsOrthographic(AcDb::OrthographicView& orthoView) const;
    bool                isUcsOrthographic(AcDb::OrthographicView& orthoView) const;
    static bool         isValidLineWeight(int weight);
    AcDb::JoinStyle     joinStyle() const;
    int                 lastSavedAsMaintenanceVersion() const;
    int                 lastSavedAsVersion() const;
    double              latitude() const;
    Adesk::UInt8        layerEval() const;
    Adesk::Int16        layerNotify() const;
    PyDbObjectId        layerTableId() const;
    PyDbObjectId        layerZero() const;
    PyDbObjectId        layoutDictionaryId()const;
    double              lensLength() const;
    Adesk::UInt8        lightGlyphDisplay() const;
    Adesk::UInt8		lightingUnits() const;
    bool				lightsInBlocks() const;
    bool				limcheck() const;
    AcGePoint2d			limmax() const;
    AcGePoint2d			limmin() const;
    PyDbObjectId		linetypeTableId() const;
    bool				lineWeightDisplay() const;
    void	            loadLineTypeFile(const std::string& ltn, const std::string& filename) const;
    double				loftAng1() const;
    double				loftAng2() const;
    double				loftMag1() const;
    double				loftMag2() const;
    Adesk::UInt8		loftNormals() const;
    Adesk::UInt16		loftParam() const;
    double				longitude() const;
    double				ltscale() const;
    Adesk::Int16		lunits() const;
    Adesk::Int16		luprec() const;
    int					maintenanceReleaseVersion() const;
    static void         markObjectNonPersistent(const PyDbObjectId& id, bool value);
    PyDbObjectId		materialDictionaryId() const;
    Adesk::Int16		maxactvp() const;
    AcDb::MeasurementValue measurement() const;
    bool				mirrtext() const;
    double				mleaderscale() const;
    PyDbObjectId		mleaderstyle() const;
    PyDbObjectId		mleaderStyleDictionaryId() const;
    PyDbObjectId		mLStyleDictionaryId() const;
    bool				msltscale() const;
    double				msOleScale() const;
    PyDbObjectId		namedObjectsDictionaryId() const;
    bool				needsRecovery() const;
    double				northDirection() const;
    Adesk::Int32		numberOfSaves() const;
    PyDbObjectContextManager objectContextManager() const;
    Adesk::UInt16		obscuredColor() const;
    Adesk::UInt8		obscuredLineType() const;
    bool				oleStartUp() const;
    int					originalFileMaintenanceVersion() const;
    std::string			originalFileName() const;
    int					originalFileSavedByMaintenanceVersion() const;
    int					originalFileSavedByVersion() const;
    int					originalFileVersion() const;
    bool				orthomode() const;
    PyDbObjectId		paperSpaceVportId() const;
    Adesk::Int8			pdfframe() const;
    Adesk::Int16		pdmode() const;
    double				pdsize() const;
    double				pelevation() const;
    AcGePoint3d			pextmax() const;
    AcGePoint3d			pextmin() const;
    Adesk::Int16		pickstyle() const;
    AcGePoint3d			pinsbase() const;
    bool				plimcheck() const;
    AcGePoint2d			plimmax() const;
    AcGePoint2d			plimmin() const;
    bool				plineEllipse() const;
    bool				plinegen() const;
    double				plinewid() const;
    PyDbObjectId		plotSettingsDictionaryId() const;
    bool				plotStyleMode() const;
    PyDbObjectId		plotStyleNameDictionaryId() const;
    Adesk::Int16		previewType() const;
    bool				psltscale() const;
    double				psolHeight() const;
    double				psolWidth() const;
    PyDbObjectId		pucsBase() const;
    PyDbObjectId		pucsname() const;
    AcGePoint3d			pucsorg() const;
    AcGeVector3d		pucsxdir() const;
    AcGeVector3d		pucsydir() const;
    void                purgeGraph(PyObjectIdGraph& graph) const;
    boost::python::list purge(const boost::python::list& pyids) const;
    bool				qtextmode() const;
    void	            reclaimMemoryFromErasedObjects(const boost::python::list& erasedObjects) const;
    PyDbObjectId		regAppTableId() const;
    bool				regenmode() const;
    void                removeReactor(PyDbDatabaseReactor& pReactor) const;
    void                registerApp(const std::string& pszAppName) const;
    void                resetTimes() const;
    void                restoreForwardingXrefSymbols() const;
    void                restoreOriginalXrefSymbols() const;
    bool				retainOriginalThumbnailBitmap() const;
    Adesk::Int16	    saveproxygraphics() const;
    PyDbObjectId		scaleListDictionaryId() const;
    PyDbObjectId		sectionViewStyle() const;
    PyDbObjectId		sectionViewStyleDictionaryId() const;
    void	            set3dDwfPrec(double DwfPrec) const;
    void	            setAngbase(double angle) const;
    void	            setAngdir(bool dir) const;
    void	            setAnnoAllVisible(bool allvis) const;
    void	            setAttdia(bool dia) const;
    void	            setAttmode(Adesk::Int16 mode) const;
    void	            setAttreq(bool req) const;
    void	            setAunits(Adesk::Int16 aunits) const;
    void	            setAuprec(Adesk::Int16 auprec) const;
    void	            setBlipmode(bool mode) const;
    void	            setCameraDisplay(bool cameraDisplay) const;
    void	            setCameraHeight(double cameraHeight) const;
    void                setCannoscale(PyDbAnnotationScale& val) const;
    void	            setCDynDisplayMode(Adesk::Int16 val) const;
    void                setCecolor(const AcCmColor& color) const;
    void	            setCeltscale(double scale) const;
    void	            setCeltype(const PyDbObjectId& id) const;
    void	            setCelweight(AcDb::LineWeight weight) const;
    void	            setCePlotStyleName(AcDb::PlotStyleNameType, const PyDbObjectId& id) const;
    void                setCetransparency(const AcCmTransparency& transparency) const;
    void	            setChamfera(double val) const;
    void	            setChamferb(double val) const;
    void	            setChamferc(double val) const;
    void	            setChamferd(double val) const;
    void	            setClayer(const PyDbObjectId& id) const;
    void	            setCmaterial(const PyDbObjectId& id) const;
    void	            setCmljust(Adesk::Int16 just) const;
    void	            setCmlscale(double scale) const;
    void	            setCmlstyleID(const PyDbObjectId& id) const;
    void	            setCoords(Adesk::Int16 coords) const;
    void	            setCshadow(Adesk::UInt8 val) const;
    void	            setDelUsedObj(Adesk::Int16 deleteObj) const;
    void	            setDgnframe(Adesk::UInt8 val) const;
    void	            setDimaso(bool aso) const;
    void	            setDimAssoc(Adesk::UInt8 val) const;
    void	            setDimfit(int fit) const;
    void	            setDimsho(bool sho) const;
    void	            setDimstyle(const PyDbObjectId& id) const;
    void                setDimstyleData1(PyDbDimStyleTableRecord& pRec) const;
    void	            setDimstyleData2(const PyDbObjectId& id) const;
    void	            setDimunit(int unit) const;
    void	            setDispSilh(bool silh) const;
    void	            setDragmode(Adesk::Int16 mode) const;
    void	            setDragVisStyle(const PyDbObjectId& id) const;
    void	            setDrawOrderCtl(Adesk::UInt8 val) const;
    void	            setDwfframe(Adesk::UInt8) const;
    void	            setElevation(double elev) const;
    void	            setEndCaps(AcDb::EndCaps type) const;
    void	            setExtmax(const AcGePoint3d& max) const;
    void	            setExtmin(const AcGePoint3d& min) const;
    void	            setFacetres(double _facetres) const;
    void	            setFilletrad(double radius) const;
    void	            setFillmode(bool mode) const;
    void	            saveAs1(const std::string& fileName) const;
    void	            saveAs2(const std::string& fileName, const bool bBakAndRename, const AcDb::AcDbDwgVersion dwgVer) const;
    void	            setFingerprintGuid(const std::string& newGuid) const;
    void				setFullSaveRequired() const;
    void	            readDwgFile1(const char* fileName) const;
    void	            readDwgFile2(const char* fileName, int mode, bool bAllowCPConversion, const std::string& password) const;
    std::string			getFilename() const;
    PyDbObjectId		currentSpaceId() const;
    PyDbObjectId		blockTableId() const;
    PyDbObjectId		modelSpaceId() const;
    void	            setGeoMarkerVisibility(bool value) const;
    void	            setHaloGap(Adesk::UInt8 val) const;
    void                setHandseed(const PyDbHandle& handle) const;
    void	            setHideText(Adesk::UInt8 val) const;
    void	            setHpInherit(const bool inherit) const;
    void	            setHpOrigin(const AcGePoint2d& origin) const;
    void	            setHyperlinkBase(const std::string& val) const;
    void	            setIndexctl(Adesk::UInt8 val) const;
    void	            setInsbase(const AcGePoint3d& base) const;
    void	            setInsunits(const AcDb::UnitsValue units) const;
    void                setInterfereColor(const AcCmColor& color) const;
    void	            setInterfereObjVisStyle(const PyDbObjectId& id) const;
    void	            setInterfereVpVisStyle(const PyDbObjectId& id) const;
    void	            setIntersectColor(Adesk::UInt16 val) const;
    void	            setIntersectDisplay(Adesk::UInt8 val) const;
    void	            setIsolines(Adesk::Int16 isolines) const;
    void	            setJoinStyle(AcDb::JoinStyle style) const;
    void	            setLatitude(double lat) const;
    void	            setLayerEval(Adesk::UInt8 val) const;
    void	            setLayerNotify(Adesk::Int16 val) const;
    void	            setLensLength(const double _lensLength) const;
    void	            setLightGlyphDisplay(Adesk::UInt8 val) const;
    void	            setLightingUnits(Adesk::UInt8 val) const;
    void	            setLightsInBlocks(bool val) const;
    void	            setLimcheck(bool check) const;
    void	            setLimmax(const AcGePoint2d& max) const;
    void	            setLimmin(const AcGePoint2d& min) const;
    void	            setLineWeightDisplay(bool display) const;
    void	            setLoftAng1(double ang1) const;
    void	            setLoftAng2(double ang2) const;
    void	            setLoftMag1(double mag1) const;
    void	            setLoftMag2(double mag2) const;
    void	            setLoftNormals(Adesk::UInt8 value) const;
    void	            setLoftParam(Adesk::UInt16 flags) const;
    void	            setLongitude(double lng) const;
    void	            setLtscale(double scale) const;
    void	            setLunits(Adesk::Int16 lunits) const;
    void	            setLuprec(Adesk::Int16 prec) const;
    void	            setMaxactvp(Adesk::Int16 max) const;
    void	            setMeasurement(AcDb::MeasurementValue type) const;
    void	            setMirrtext(bool mirror) const;
    void	            setMLeaderscale(double scale) const;
    void	            setMLeaderstyle(const PyDbObjectId& objId) const;
    void	            setMsltscale(bool val) const;
    void	            setMsOleScale(double val) const;
    void	            setNorthDirection(double northdir) const;
    void	            setObscuredColor(Adesk::UInt16 val) const;
    void	            setObscuredLineType(Adesk::UInt8 val) const;
    void	            setOleStartUp(bool val) const;
    void	            setOrthomode(bool mode) const;
    void	            setPdfframe(Adesk::Int8 val) const;
    void	            setPdmode(Adesk::Int16 mode) const;
    void	            setPdsize(double size) const;
    void	            setPelevation(double elev) const;
    void	            setPextmax(const AcGePoint3d& max) const;
    void	            setPextmin(const AcGePoint3d& min) const;
    void	            setPickstyle(Adesk::Int16 style) const;
    void	            setPinsbase(const AcGePoint3d& base) const;
    void	            setPlimcheck(bool check) const;
    void	            setPlimmax(const AcGePoint2d& max) const;
    void	            setPlimmin(const AcGePoint2d& min) const;
    void	            setPlineEllipse(bool pline) const;
    void	            setPlinegen(bool gen) const;
    void	            setPlinewid(double width) const;
    void	            setPreviewType(Adesk::Int16 val) const;
    void	            setProjectName(const std::string& val) const;
    void	            setPsltscale(bool scale) const;
    void	            setPsolHeight(double height) const;
    void	            setPsolWidth(double width) const;
    void	            setPucs(const AcGePoint3d& ucsOrigin, const AcGeVector3d& ucsXDir, const AcGeVector3d& ucsYDir) const;
    void	            setPucsBase(const PyDbObjectId& ucsid) const;
    void	            setPucsname(const PyDbObjectId& ucsRecId) const;
    void	            setQtextmode(bool mode) const;
    void	            setRealWorldScale(const bool realWorldScale) const;
    void	            setRegenmode(bool mode) const;
    void				setRetainOriginalThumbnailBitmap(bool retain) const;
    void	            setSaveproxygraphics(Adesk::Int16 saveimg) const;
    void	            setSectionViewStyle(const PyDbObjectId& objId) const;
    //bool setSecurityParams(const SecurityParams* pSecParams,bool bSetDbMod = true) const;//TODO:
    //const SecurityParams* cloneSecurityParams() const;
    //static void disposeSecurityParams(const SecurityParams* pSecParams) const;
    void	            setShadedge(Adesk::Int16 mode) const;
    void	            setShadedif(Adesk::Int16 dif) const;
    void	            setShadowPlaneLocation(double val) const;
    void	            setShowHist(Adesk::UInt8 val) const;
    void	            setSketchinc(double inc) const;
    void	            setSkpoly(bool asPoly) const;
    void	            setSolidHist(Adesk::UInt8 val) const;
    void	            setSortEnts(Adesk::UInt8 sortEnts) const;
    void	            setSplframe(bool disp) const;
    void	            setSplinesegs(Adesk::Int16 segs) const;
    void	            setSplinetype(Adesk::Int16 type) const;
    void	            setStepSize(double stepSize) const;
    void	            setStepsPerSec(double stepsPerSec) const;
    void	            setStyleSheet(const std::string& val) const;
    void	            setSurftab1(Adesk::Int16 tab1) const;
    void	            setSurftab2(Adesk::Int16 tab2) const;
    void	            setSurftype(Adesk::Int16 type) const;
    void	            setSurfu(Adesk::Int16 v) const;
    void	            setSurfv(Adesk::Int16 v) const;
    void	            setTablestyle(const PyDbObjectId& objId) const;
    void	            setTextsize(double size) const;
    void	            setTextstyle(const PyDbObjectId& objId) const;
    void	            setThickness(double thickness) const;
    void	            setTilemode(bool mode) const;
    void	            setTimeZone(AcDb::TimeZone tz) const;
    void	            setTimeZoneAsUtcOffset(double offset) const;
    void	            setTracewid(double width) const;
    void	            setTreedepth(Adesk::Int16 depth) const;
    void	            setTStackAlign(int val) const;
    void	            setTStackSize(int val) const;
    void	            setUcs(const AcGePoint3d& ucsOrigin, const AcGeVector3d& ucsXDir, const AcGeVector3d& ucsYDir) const;
    void	            setUcsBase(const PyDbObjectId& ucsid) const;
    void	            setUcsname(const PyDbObjectId& ucsRecId) const;
    void	            setUnitmode(Adesk::Int16 mode) const;
    void	            setUpdateThumbnail(Adesk::UInt8 val) const;
    void	            setUseri1(Adesk::Int16 val) const;
    void	            setUseri2(Adesk::Int16 val) const;
    void	            setUseri3(Adesk::Int16 val) const;
    void	            setUseri4(Adesk::Int16 val) const;
    void	            setUseri5(Adesk::Int16 val) const;
    void	            setUserr1(double val) const;
    void	            setUserr2(double val) const;
    void	            setUserr3(double val) const;
    void	            setUserr4(double val) const;
    void	            setUserr5(double val) const;
    void	            setUsrtimer(bool timer) const;
    void	            setVersionGuid(const std::string& pNewGuid) const;
    void	            setViewportScaleDefault(double newDefaultVPScale) const;
    void	            setVisretain(bool retain) const;
    void	            setWorldPucsBaseOrigin(const AcGePoint3d& origin, AcDb::OrthographicView orthoView) const;
    void	            setWorldUcsBaseOrigin(const AcGePoint3d& origin, AcDb::OrthographicView orthoView) const;
    void	            setWorldview(bool view) const;
    void	            setXclipFrame(Adesk::UInt8 disp) const;
    void	            setXrefEditEnabled(bool enable) const;
    Adesk::Int16	    shadedge() const;
    Adesk::Int16		shadedif() const;
    double				shadowPlaneLocation() const;
    Adesk::UInt8		showHist() const;
    double				sketchinc() const;
    bool				skpoly() const;
    Adesk::UInt8		solidHist() const;
    Adesk::UInt8		sortEnts() const;
    bool				splframe() const;
    Adesk::Int16		splinesegs() const;
    Adesk::Int16		splinetype() const;
    double				stepSize() const;
    double				stepsPerSec() const;
    Adesk::Int16		surftab1() const;
    Adesk::Int16		surftab2() const;
    Adesk::Int16		surftype() const;
    Adesk::Int16		surfu() const;
    Adesk::Int16		surfv() const;
    PyDbObjectId		tablestyle() const;
    PyDbObjectId		tableStyleDictionaryId() const;
    PyDbDate            tdcreate() const;
    PyDbDate            tdindwg() const;
    PyDbDate            tducreate() const;
    PyDbDate            tdupdate() const;
    PyDbDate            tdusrtimer() const;
    PyDbDate            tduupdate() const;
    double				textsize() const;
    PyDbObjectId		textstyle() const;
    PyDbObjectId		textStyleTableId() const;
    double				thickness() const;
    bool				tilemode() const;
    Adesk::UInt8		tileModeLightSynch() const;
    AcDb::TimeZone		timeZone() const;
    double				tracewid() const;
    PyDbTransactionManager transactionManager() const;
    Adesk::Int16		treedepth() const;
    int					tstackalign() const;
    int					tstacksize() const;
    PyDbObjectId		ucsBase() const;
    PyDbObjectId		ucsname() const;
    AcGePoint3d			ucsorg() const;
    PyDbObjectId		UCSTableId() const;
    AcGeVector3d		ucsxdir() const;
    AcGeVector3d		ucsydir() const;
    bool				undoRecording() const;
    Adesk::Int16		unitmode() const;
    void	            updateDataLink(AcDb::UpdateDirection nDir, AcDb::UpdateOption nOption) const;
    void	            updateExt(bool doBestFit) const;
    Adesk::UInt8	    updateThumbnail() const;
    Adesk::Int16	    useri1() const;
    Adesk::Int16	    useri2() const;
    Adesk::Int16	    useri3() const;
    Adesk::Int16	    useri4() const;
    Adesk::Int16	    useri5() const;
    double				userr1() const;
    double				userr2() const;
    double				userr3() const;
    double				userr4() const;
    double				userr5() const;
    bool				usrtimer() const;
    double				viewportScaleDefault() const;
    PyDbObjectId		viewportTableId() const;
    PyDbObjectId		viewTableId() const;
    bool				visretain() const;
    PyDbObjectId		visualStyleDictionaryId() const;

    void	            wblock1(PyDbDatabase& pOutputDb, const boost::python::list& outObjIds, const AcGePoint3d& basePoint, AcDb::DuplicateRecordCloning drc) const;
    PyDbDatabase	    wblock2(const boost::python::list& outObjIds, const AcGePoint3d& basePoint) const;
    PyDbDatabase	    wblock3(const PyDbObjectId& blockId) const;
    PyDbDatabase	    wblock4() const;

    void                abortDeepClone(PyDbIdMapping& idMap) const;

    void                deepCloneObjects1(const boost::python::list& objectIds,
        const PyDbObjectId& owner, PyDbIdMapping& idMap) const;

    void                deepCloneObjects2(const boost::python::list& objectIds,
        const PyDbObjectId& owner, PyDbIdMapping& idMap, bool deferXlation) const;

    void                wblockCloneObjects1(const boost::python::list& objectIds, const
        PyDbObjectId& owner, PyDbIdMapping& idMap, AcDb::DuplicateRecordCloning drc) const;

    void                wblockCloneObjects2(const boost::python::list& objectIds, const
        PyDbObjectId& owner, PyDbIdMapping& idMap, AcDb::DuplicateRecordCloning drc, bool deferXlation) const;

    AcGePoint3d			worldPucsBaseOrigin(AcDb::OrthographicView orthoView) const;
    AcGePoint3d			worldUcsBaseOrigin(AcDb::OrthographicView orthoView) const;
    bool				worldview() const;
    Adesk::UInt8		xclipFrame() const;
    PyDbObjectId		xrefBlockId() const;
    bool				xrefEditEnabled() const;
    //
    static std::string	className();
public:
    AcDbDatabase* impObj(const std::source_location& src = std::source_location::current()) const;
};

#pragma pack (pop)