from __future__ import annotations

from typing import Any, ClassVar, Self, overload

import wx

from pyrx import Brx as PyBrx
from pyrx import Db as PyDb
from pyrx import Ge as PyGe
from pyrx.doc_utils.boost_meta import _BoostPythonEnum

eAc3DAngle: ConstraintType  # 1
eAc3DCoincident: ConstraintType  # 2
eAc3DConcentric: ConstraintType  # 3
eAc3DDistance: ConstraintType  # 4
eAc3DFix: ConstraintType  # 5
eAc3DMajorRadius: ConstraintType  # 6
eAc3DMinorRadius: ConstraintType  # 7
eAc3DParallel: ConstraintType  # 8
eAc3DPerpendicular: ConstraintType  # 9
eAc3DPlanarAngle: ConstraintType  # 10
eAc3DRadius: ConstraintType  # 11
eAc3DRigidSet: ConstraintType  # 12
eAc3DTangent: ConstraintType  # 13
eAcCircularArray: ConstraintType  # 14
eAcObjectAngle: ConstraintType  # 15
eAcPath: ConstraintType  # 16
eAcUnknown: ConstraintType  # 0
eAuto: VariableEGdMode  # 2
eBim: LicensedFeature  # 2
eBoolean: MechanicalPropertyType  # 3
eCSOrigin: ConstraintArgCoordSysObj  # 0
eCSX: ConstraintArgCoordSysObj  # 1
eCSXY: ConstraintArgCoordSysObj  # 4
eCSY: ConstraintArgCoordSysObj  # 2
eCSYZ: ConstraintArgCoordSysObj  # 5
eCSZ: ConstraintArgCoordSysObj  # 3
eCSZX: ConstraintArgCoordSysObj  # 6
eCommunicator: LicensedFeature  # 1
eCore: LicensedFeature  # 0
eDirectionsAny: ConstraintDirections  # 0
eDirectionsKeep: ConstraintDirections  # 3
eDirectionsOpposite: ConstraintDirections  # 2
eDirectionsSame: ConstraintDirections  # 1
eInteger: MechanicalPropertyType  # 1
eMeasurementModeBoundary: ConstraintMeasurementMode  # 1
eMeasurementModeCenter: ConstraintMeasurementMode  # 0
eMeasurementModeCentralPoint: ConstraintMeasurementMode  # 2
eMechanical: LicensedFeature  # 3
eOff: VariableEGdMode  # 0
eOn: VariableEGdMode  # 1
ePlacementAny: ConstraintPlacement  # 0
ePlacementInside: ConstraintPlacement  # 2
ePlacementKeep: ConstraintPlacement  # 3
ePlacementOutside: ConstraintPlacement  # 1
eReal: MechanicalPropertyType  # 2
eString: MechanicalPropertyType  # 4
eUndefined: VariableExposeMode  # 2

class BlockParameter:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def className() -> str: ...
    def expression(self, /) -> str: ...
    def hasStringValue(self, /) -> bool: ...
    def setExpression(self, expr: str, /) -> None: ...
    def stringValue(self, /) -> str: ...
    def value(self, /) -> float: ...

class Constraint:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    def arguments(self, /) -> list[PyDb.FullSubentPath]: ...
    @staticmethod
    def className() -> str: ...
    def getArguments(self, /) -> list[PyBrx.ConstraintArgument]: ...
    def getBlockId(self, /) -> PyDb.ObjectId: ...
    def getDimension(self, /) -> PyDb.ObjectId: ...
    def getDirections(self, /) -> ConstraintDirections: ...
    def getMeasurementMode(self, argIndex: int, /) -> ConstraintMeasurementMode: ...
    def getPlacement(self, argIndex: int, /) -> ConstraintPlacement: ...
    def getType(self, /) -> ConstraintType: ...
    def hasParameter(self, /) -> bool: ...
    def isDimensional(self, /) -> bool: ...
    def isEnabled(self, /) -> bool: ...
    def name(self, /) -> str: ...
    def nodeId(self, /) -> int: ...
    def parameter(self, /) -> Variable: ...
    def setDirections(self, flag: PyBrx.ConstraintDirections, /) -> None: ...
    def setEnabled(self, flag: bool, /) -> None: ...
    def setMeasurementMode(
        self, flag: PyBrx.ConstraintMeasurementMode, argIndex: int, /
    ) -> None: ...
    def setName(self, name: str, /) -> None: ...
    def setPlacement(self, flag: PyBrx.ConstraintPlacement, argIndex: int, /) -> None: ...

class ConstraintArgCoordSysObj(_BoostPythonEnum):
    eCSOrigin: ClassVar[Self]  # 0
    eCSX: ClassVar[Self]  # 1
    eCSY: ClassVar[Self]  # 2
    eCSZ: ClassVar[Self]  # 3
    eCSXY: ClassVar[Self]  # 4
    eCSYZ: ClassVar[Self]  # 5
    eCSZX: ClassVar[Self]  # 6

class ConstraintArgument:
    @overload
    def __init__(self, /) -> None: ...
    @overload
    def __init__(self, subpath: PyDb.FullSubentPath, /) -> None: ...
    @overload
    def __init__(self, val: PyBrx.ConstraintArgCoordSysObj, /) -> None: ...
    @overload
    def __init__(
        self, subpath: PyDb.FullSubentPath, val: PyBrx.ConstraintArgCoordSysObj, /
    ) -> None: ...
    @overload
    def __init__(self, *args) -> None: ...
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def className() -> str: ...
    def coordinateSystemObject(self, /) -> ConstraintArgCoordSysObj: ...
    def isCoordinateSystemObject(self, /) -> bool: ...
    def path(self, /) -> PyDb.FullSubentPath: ...

class ConstraintDirections(_BoostPythonEnum):
    eDirectionsAny: ClassVar[Self]  # 0
    eDirectionsSame: ClassVar[Self]  # 1
    eDirectionsOpposite: ClassVar[Self]  # 2
    eDirectionsKeep: ClassVar[Self]  # 3

class ConstraintMeasurementMode(_BoostPythonEnum):
    eMeasurementModeCenter: ClassVar[Self]  # 0
    eMeasurementModeBoundary: ClassVar[Self]  # 1
    eMeasurementModeCentralPoint: ClassVar[Self]  # 2

class ConstraintPlacement(_BoostPythonEnum):
    ePlacementAny: ClassVar[Self]  # 0
    ePlacementOutside: ClassVar[Self]  # 1
    ePlacementInside: ClassVar[Self]  # 2
    ePlacementKeep: ClassVar[Self]  # 3

class ConstraintType(_BoostPythonEnum):
    eAcUnknown: ClassVar[Self]  # 0
    eAc3DAngle: ClassVar[Self]  # 1
    eAc3DCoincident: ClassVar[Self]  # 2
    eAc3DConcentric: ClassVar[Self]  # 3
    eAc3DDistance: ClassVar[Self]  # 4
    eAc3DFix: ClassVar[Self]  # 5
    eAc3DMajorRadius: ClassVar[Self]  # 6
    eAc3DMinorRadius: ClassVar[Self]  # 7
    eAc3DParallel: ClassVar[Self]  # 8
    eAc3DPerpendicular: ClassVar[Self]  # 9
    eAc3DPlanarAngle: ClassVar[Self]  # 10
    eAc3DRadius: ClassVar[Self]  # 11
    eAc3DRigidSet: ClassVar[Self]  # 12
    eAc3DTangent: ClassVar[Self]  # 13
    eAcCircularArray: ClassVar[Self]  # 14
    eAcObjectAngle: ClassVar[Self]  # 15
    eAcPath: ClassVar[Self]  # 16

class ConstraintsGroup:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    def addConstraintArgs(
        self, type: PyBrx.ConstraintType, args: list[PyBrx.ConstraintArgument], /
    ) -> Constraint: ...
    def addConstraintSubents(
        self, type: PyBrx.ConstraintType, paths: list[PyDb.FullSubentPath], /
    ) -> Constraint: ...
    @staticmethod
    def className() -> str: ...
    def constraints(self, /) -> list[PyBrx.Constraint]: ...
    def deleteConstraint(self, constraint: PyBrx.Constraint, /) -> None: ...
    def evaluate(self, /) -> None: ...
    def getBlockId(self, /) -> PyDb.ObjectId: ...
    def getConstraintByNodeId(self, nodeId: int, /) -> Constraint: ...
    def getSketchPlane(self, /) -> PyGe.Plane: ...
    def hasSketchPlane(self, /) -> bool: ...
    def isTransient(self, /) -> bool: ...

class Core:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def blockParameterHasStringValue(blockRefId: PyDb.ObjectId, name: str, /) -> bool: ...
    @staticmethod
    def effectiveBlockRefName(blockRefId: PyDb.ObjectId, /) -> str: ...
    @staticmethod
    def effectiveBlockTableRecord(blockRefId: PyDb.ObjectId, /) -> PyDb.ObjectId: ...
    @staticmethod
    def getAllConstraintsGroups(db: PyDb.Database, /) -> list[PyBrx.ConstraintsGroup]: ...
    @staticmethod
    def getBlockParameter(blockRefId: PyDb.ObjectId, name: str, /) -> BlockParameter: ...
    @staticmethod
    def getBlockParameterExpression(blockRefId: PyDb.ObjectId, name: str, /) -> str: ...
    @staticmethod
    def getBlockParameterStringValue(blockRefId: PyDb.ObjectId, name: str, /) -> str: ...
    @staticmethod
    def getBlockParameterValue(blockRefId: PyDb.ObjectId, name: str, /) -> float: ...
    @staticmethod
    def getBlockParametersNames(blockRefId: PyDb.ObjectId, /) -> list[str]: ...
    @staticmethod
    def getConstraintsGroup(
        blockRefId: PyDb.ObjectId, createIfNotExist: bool = False, /
    ) -> ConstraintsGroup: ...
    @staticmethod
    def getEntityGuiName(entId: PyDb.ObjectId, /) -> str: ...
    @staticmethod
    def getOpenObjects() -> list[PyDb.ObjectId]: ...
    @staticmethod
    def isLicenseAvailable(val: PyBrx.LicensedFeature, /) -> bool: ...
    @staticmethod
    def removeConstraints(id: PyDb.ObjectId, /) -> bool: ...
    @staticmethod
    def removeConstraintsFromDatabase(db: PyDb.Database, /) -> bool: ...
    @staticmethod
    def setBlockParameterExpression(
        blockRefId: PyDb.ObjectId, name: str, expr: str, /
    ) -> None: ...
    @staticmethod
    def setEntityGuiName(entId: PyDb.ObjectId, name: str, /) -> None: ...

class DbProperties:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def dumpAll(id: PyDb.ObjectId, /) -> None: ...
    @staticmethod
    def getValue(id: PyDb.ObjectId, name: str, /) -> PyDb.AcValue: ...
    @staticmethod
    def isReadOnly(id: PyDb.ObjectId, name: str, /) -> tuple: ...
    @staticmethod
    def isValid(id: PyDb.ObjectId, name: str, /) -> tuple: ...
    @staticmethod
    def listAll(id: PyDb.ObjectId, /) -> list[str]: ...
    @staticmethod
    def setValue(id: PyDb.ObjectId, name: str, val: PyDb.AcValue, /) -> None: ...

class DesignTable:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def className() -> str: ...
    def configurations(self, /) -> list[PyBrx.DesignTableConfiguration]: ...
    def currentConfiguration(self, /) -> DesignTableConfiguration: ...
    @staticmethod
    def getAllDesignTables(blockId: PyDb.ObjectId, /) -> list[PyBrx.DesignTable]: ...
    def getBlockId(self, /) -> PyDb.ObjectId: ...
    def keyName(self, /) -> str: ...
    def name(self, /) -> str: ...

class DesignTableConfiguration:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def className() -> str: ...
    def name(self, /) -> str: ...
    def variables(self, /) -> list[PyBrx.DesignTableConfigurationEntry]: ...

class DesignTableConfigurationEntry:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def className() -> str: ...
    def isDoubleValue(self, /) -> bool: ...
    def value(self, /) -> str: ...
    def valueAsDouble(self, /) -> float: ...
    def variableName(self, /) -> str: ...

class LicensedFeature(_BoostPythonEnum):
    eCore: ClassVar[Self]  # 0
    eCommunicator: ClassVar[Self]  # 1
    eBim: ClassVar[Self]  # 2
    eMechanical: ClassVar[Self]  # 3

class MechanicalPropertyDefinition:
    def __init__(self, /) -> None: ...
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def className() -> str: ...
    def doesExist(self, /) -> bool: ...
    def enumValues(self, /) -> list[tuple[str, str]]: ...
    def isNull(self, /) -> bool: ...
    def label(self, /) -> str: ...
    def name(self, /) -> str: ...
    def setEnumValues(self, aNewEnumValues: list[tuple[str, str]], /) -> None: ...
    def setLabel(self, newLabel: str, /) -> None: ...
    def setType(self, newTypeName: PyBrx.MechanicalPropertyType, /) -> None: ...
    def type(self, /) -> MechanicalPropertyType: ...

class MechanicalPropertySet:
    def __init__(self, /) -> None: ...
    def __reduce__(self, /) -> Any: ...
    def addProperty(
        self, propertyName: str, propertyType: PyBrx.MechanicalPropertyType, label: str = ..., /
    ) -> MechanicalPropertyDefinition: ...
    def categoryLabel(self, /) -> str: ...
    def categoryName(self, /) -> str: ...
    @staticmethod
    def className() -> str: ...
    @overload
    def createCategory(db: PyDb.Database, propertyName: str, /) -> MechanicalPropertySet: ...
    @overload
    def createCategory(
        db: PyDb.Database, propertyName: str, isPerInstance: bool, /
    ) -> MechanicalPropertySet: ...
    @overload
    def createCategory(
        db: PyDb.Database, propertyName: str, isPerInstance: bool, label: str, /
    ) -> MechanicalPropertySet: ...
    @overload
    def createCategory(self, *args) -> MechanicalPropertySet: ...
    @staticmethod
    def getAllCategories() -> Any: ...
    def getAllCustomProperties(self, /) -> list[PyBrx.MechanicalPropertyDefinition]: ...
    def getCategoryByName(db: PyDb.Database, propertyName: str, /) -> MechanicalPropertySet: ...
    def getPropertyByName(self, propertyName: str, /) -> MechanicalPropertyDefinition: ...
    def isNull(self, /) -> bool: ...
    def isPerInstance(self, /) -> bool: ...

class MechanicalPropertyType(_BoostPythonEnum):
    eUndefined: ClassVar[Self]  # 0
    eInteger: ClassVar[Self]  # 1
    eReal: ClassVar[Self]  # 2
    eBoolean: ClassVar[Self]  # 3
    eString: ClassVar[Self]  # 4

class PyBrxPanel:
    def __init__(self, name: str, configKey: str = ..., /) -> None: ...
    def __reduce__(self, /) -> Any: ...
    def backgroundColor(self, /) -> int: ...
    def create(self, panel: wx.Panel, /) -> bool: ...
    def destroy(self, /) -> None: ...
    def isFloating(self, /) -> bool: ...
    def setIcon(self, imagePath: str, /) -> None: ...
    def tabTextColor(self, /) -> int: ...

class Variable:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def className() -> str: ...
    def erase(self, /) -> None: ...
    def exposed(self, /) -> VariableExposeMode: ...
    def expression(self, /) -> str: ...
    def geometryDrivenMode(self, /) -> VariableEGdMode: ...
    def getBlockId(self, /) -> PyDb.ObjectId: ...
    @staticmethod
    def getByName(
        blockId: PyDb.ObjectId, name: str, createIfNotExist: bool = False, /
    ) -> Variable: ...
    @staticmethod
    def getFromBlock(blockId: PyDb.ObjectId, /) -> list[PyBrx.Variable]: ...
    @staticmethod
    def has(blockId: PyDb.ObjectId, name: str, /) -> bool: ...
    def hasLowerBound(self, /) -> bool: ...
    def hasUpperBound(self, /) -> bool: ...
    def isAnonymous(self, /) -> bool: ...
    def lowerBound(self, /) -> float: ...
    def name(self, /) -> str: ...
    def setExposed(self, val: PyBrx.VariableExposeMode, /) -> None: ...
    def setExpression(self, name: str, /) -> None: ...
    def setGeometryDrivenMode(self, val: PyBrx.VariableEGdMode, /) -> None: ...
    def setLowerBound(self, val: float, /) -> None: ...
    def setName(self, name: str, /) -> None: ...
    def setValue(self, val: float, /) -> None: ...
    def unsetUpperBound(self, val: float, /) -> None: ...
    def upperBound(self, /) -> float: ...
    def value(self, /) -> float: ...

class VariableEGdMode(_BoostPythonEnum):
    eOff: ClassVar[Self]  # 0
    eOn: ClassVar[Self]  # 1
    eAuto: ClassVar[Self]  # 2

class VariableExposeMode(_BoostPythonEnum):
    eOff: ClassVar[Self]  # 0
    eOn: ClassVar[Self]  # 1
    eUndefined: ClassVar[Self]  # 2
