from __future__ import annotations

from typing import Any, ClassVar, Self, overload

import wx

from pyrx import Brx as PyBrx
from pyrx import Db as PyDb
from pyrx.doc_utils.boost_meta import _BoostPythonEnum

eBim: LicensedFeature  # 2
eBoolean: MechanicalPropertyType  # 3
eCommunicator: LicensedFeature  # 1
eCore: LicensedFeature  # 0
eInteger: MechanicalPropertyType  # 1
eMechanical: LicensedFeature  # 3
eReal: MechanicalPropertyType  # 2
eString: MechanicalPropertyType  # 4
eUndefined: MechanicalPropertyType  # 0

class Core:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def getOpenObjects() -> list: ...
    @staticmethod
    def isLicenseAvailable(val: PyBrx.LicensedFeature, /) -> bool: ...

class DbProperties:
    def __init__(self) -> None:
        """
        Raises an exception.
        This class cannot be instantiated from Python.
        """
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def dumpAll(id: PyDb.ObjectId, /) -> None: ...
    @staticmethod
    def getValue(id: PyDb.ObjectId, name: str, /) -> PyDb.AcValue: ...
    @staticmethod
    def isReadOnly(id: PyDb.ObjectId, name: str, /) -> tuple: ...
    @staticmethod
    def isValid(id: PyDb.ObjectId, name: str, /) -> tuple: ...
    @staticmethod
    def listAll(id: PyDb.ObjectId, /) -> list: ...
    @staticmethod
    def setValue(id: PyDb.ObjectId, name: str, val: PyDb.AcValue, /) -> None: ...

class LicensedFeature(_BoostPythonEnum):
    eCore: ClassVar[Self]  # 0
    eCommunicator: ClassVar[Self]  # 1
    eBim: ClassVar[Self]  # 2
    eMechanical: ClassVar[Self]  # 3

class MechanicalPropertyDefinition:
    def __init__(self, /) -> None: ...
    def __reduce__(self, /) -> Any: ...
    @staticmethod
    def className() -> str: ...
    def doesExist(self, /) -> bool: ...
    def enumValues(self, /) -> list: ...
    def isNull(self, /) -> bool: ...
    def label(self, /) -> str: ...
    def name(self, /) -> str: ...
    def setEnumValues(self, aNewEnumValues: list[tuple[str, str]], /) -> None: ...
    def setLabel(self, newLabel: str, /) -> None: ...
    def setType(self, newTypeName: PyBrx.MechanicalPropertyType, /) -> None: ...
    def type(self, /) -> MechanicalPropertyType: ...

class MechanicalPropertySet:
    def __init__(self, /) -> None: ...
    def __reduce__(self, /) -> Any: ...
    def addProperty(
        self, propertyName: str, propertyType: PyBrx.MechanicalPropertyType, label: str = ..., /
    ) -> MechanicalPropertyDefinition: ...
    def categoryLabel(self, /) -> str: ...
    def categoryName(self, /) -> str: ...
    @staticmethod
    def className() -> str: ...
    @overload
    def createCategory(db: PyDb.Database, propertyName: str, /) -> MechanicalPropertySet: ...
    @overload
    def createCategory(
        db: PyDb.Database, propertyName: str, isPerInstance: bool, /
    ) -> MechanicalPropertySet: ...
    @overload
    def createCategory(
        db: PyDb.Database, propertyName: str, isPerInstance: bool, label: str, /
    ) -> MechanicalPropertySet: ...
    @overload
    def createCategory(self, *args) -> MechanicalPropertySet: ...
    @staticmethod
    def getAllCategories() -> Any: ...
    def getAllCustomProperties(self, /) -> list: ...
    def getCategoryByName(db: PyDb.Database, propertyName: str, /) -> MechanicalPropertySet: ...
    def getPropertyByName(self, propertyName: str, /) -> MechanicalPropertyDefinition: ...
    def isNull(self, /) -> bool: ...
    def isPerInstance(self, /) -> bool: ...

class MechanicalPropertyType(_BoostPythonEnum):
    eUndefined: ClassVar[Self]  # 0
    eInteger: ClassVar[Self]  # 1
    eReal: ClassVar[Self]  # 2
    eBoolean: ClassVar[Self]  # 3
    eString: ClassVar[Self]  # 4

class PyBrxPanel:
    def __init__(self, name: str, configKey: str = ..., /) -> None: ...
    def __reduce__(self, /) -> Any: ...
    def backgroundColor(self, /) -> int: ...
    def create(self, panel: wx.Panel, /) -> bool: ...
    def destroy(self, /) -> None: ...
    def isFloating(self, /) -> bool: ...
    def setIcon(self, imagePath: str, /) -> None: ...
    def tabTextColor(self, /) -> int: ...
