name: Mypy Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  type-check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Mypy and Standard Types Only
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-setuptools

      - name: Run mypy with ignored third-party imports
        run: mypy . --ignore-missing-imports
