name: Pytest Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run Pytest
        run: |
          TEST_PATHS=(
            #    tests/test_ap
            #    tests/test_commands
            #    tests/test_core
            #    tests/test_db
            tests/test_doc_utils/test_misc.py
            tests/test_doc_utils/test_parse_docstring.py
            #    tests/test_doc_utils/test_pyi_gen.py
            #    tests/test_utils
            #    tests/test_console.py
          )
          pytest "${TEST_PATHS[@]}"
